import Foundation

struct WordHuntGame {
    let grid: [[Character]]   // 4×4
    let seed: Int
    private(set) var validWords: Set<String> = []

    static let gridSize = 4

    init(grid: [[Character]], seed: Int) {
        self.grid = grid
        self.seed = seed
        self.validWords = Self.findAllWords(in: grid)
    }

    // MARK: - Path validation

    /// Returns true if `word` can be traced as a valid adjacency path in the grid.
    func canForm(_ word: String) -> Bool {
        let chars = Array(word.uppercased())
        guard chars.count >= 3 else { return false }
        for r in 0..<Self.gridSize {
            for c in 0..<Self.gridSize {
                if grid[r][c] == chars[0] {
                    var visited = [[Bool]](repeating: [Bool](repeating: false, count: Self.gridSize), count: Self.gridSize)
                    visited[r][c] = true
                    if dfs(chars: chars, index: 1, row: r, col: c, visited: &visited) { return true }
                }
            }
        }
        return false
    }

    private func dfs(chars: [Character], index: Int, row: Int, col: Int, visited: inout [[Bool]]) -> Bool {
        if index == chars.count { return true }
        for (nr, nc) in Self.neighbors(row: row, col: col) {
            guard !visited[nr][nc], grid[nr][nc] == chars[index] else { continue }
            visited[nr][nc] = true
            if dfs(chars: chars, index: index + 1, row: nr, col: nc, visited: &visited) { return true }
            visited[nr][nc] = false
        }
        return false
    }

    static func neighbors(row: Int, col: Int) -> [(Int, Int)] {
        var result: [(Int, Int)] = []
        for dr in -1...1 {
            for dc in -1...1 {
                guard dr != 0 || dc != 0 else { continue }
                let nr = row + dr, nc = col + dc
                if nr >= 0 && nr < gridSize && nc >= 0 && nc < gridSize {
                    result.append((nr, nc))
                }
            }
        }
        return result
    }

    // MARK: - Score

    static func score(for word: String) -> Int {
        switch word.count {
        case 3:      return 1
        case 4:      return 2
        case 5:      return 3
        case 6:      return 4
        default:     return 5
        }
    }

    // MARK: - Grid generation

    static func generate(seed: Int) -> WordHuntGame {
        // Weighted letter bag — roughly English Scrabble frequencies
        let bag: [Character] = Array(
            "AAAAAAAAABBCCDDDDEEEEEEEEEEEEFFGGGHHIIIIIIIIJKLLLLMMNNNNNNOOOOOOOOPPQRRRRRRSSSSTTTTTTTUUUUVVWWXYYZ"
        )
        var s = UInt64(bitPattern: Int64(seed &* 6364136223846793005 &+ 1442695040888963407))
        var flat: [Character] = []
        for _ in 0..<(gridSize * gridSize) {
            s = s &* 6364136223846793005 &+ 1442695040888963407
            flat.append(bag[Int(s >> 33) % bag.count])
        }
        let grid = (0..<gridSize).map { r in Array(flat[(r * gridSize)..<(r * gridSize + gridSize)]) }
        return WordHuntGame(grid: grid, seed: seed)
    }

    // MARK: - Pre-compute all valid words in this grid

    private static func findAllWords(in grid: [[Character]]) -> Set<String> {
        var found = Set<String>()
        let game = WordHuntGame(grid: grid, seed: 0, validWords: Set())   // temp without recursion
        for word in WordDictionary.words {
            if game.canForm(word) { found.insert(word) }
        }
        return found
    }

    // Private init used during pre-computation
    private init(grid: [[Character]], seed: Int, validWords: Set<String>) {
        self.grid = grid
        self.seed = seed
        self.validWords = validWords
    }
}

// MARK: - Embedded dictionary

enum WordDictionary {
    static let words: Set<String> = {
        var s = wordsBase
        s.formUnion(words6)
        s.formUnion(words7)
        s.formUnion(words8)
        return s
    }()
    static let wordsBase: Set<String> = [
        // 3-letter words
        "ACE","ACT","ADD","ADO","AFT","AGE","AGO","AHI","AID","AIM","AIR","ALA","ALE","ALL","ALP","ALT","AMI","AMP",
        "ANA","AND","ANE","ANI","ANT","APE","APO","APT","ARC","ARE","ARK","ARM","ARS","ART","ASH","ASK","ATE","AUK",
        "AVE","AWE","AWL","AWN","AXE","AYE","BAD","BAG","BAH","BAN","BAR","BAS","BAT","BAY","BED","BEE","BEN","BET",
        "BEY","BIG","BIT","BOA","BOD","BOG","BOP","BOW","BOX","BOY","BRO","BUD","BUG","BUN","BUS","BUT","BUY","BYE",
        "CAB","CAD","CAN","CAP","CAR","CAT","CAW","CEE","COB","COD","COG","COL","CON","COO","COP","COS","COT","COW",
        "CRY","CUB","CUE","CUP","CUR","CUT","DAD","DAM","DAY","DEE","DEN","DEW","DID","DIG","DIM","DIP","DOC","DOE",
        "DOG","DOH","DOM","DOP","DOT","DOW","DRY","DUB","DUD","DUE","DUG","DUH","DUN","DUO","DYE","EAR","EAT","EEL",
        "EFF","EGG","ELF","ELK","ELM","EMS","EMU","END","ERA","ETA","EWE","EYE","FAD","FAH","FAN","FAR","FAT","FAX",
        "FED","FEH","FEW","FEZ","FIB","FIG","FIN","FIT","FLY","FOB","FOE","FOG","FON","FOR","FOX","FOP","FRY","FUN",
        "FUR","GAD","GAL","GAM","GAP","GAS","GAY","GEE","GEL","GEM","GEN","GET","GIB","GIG","GIT","GNU","GOB","GOD",
        "GOT","GUM","GUN","GUT","GUY","GYM","HAD","HAG","HAM","HAP","HAS","HAT","HAY","HEN","HEP","HER","HEY","HIE",
        "HIM","HIN","HIT","HOB","HOD","HOG","HON","HOO","HOP","HOT","HOW","HOY","HUB","HUE","HUG","HUM","HUT","ICE",
        "ICY","ILL","INN","ION","IRE","IVY","JAB","JAM","JAR","JAW","JAY","JEE","JET","JIB","JIG","JIN","JOB","JOG",
        "JOT","JOY","JUG","JUT","KAY","KEG","KEN","KID","KIN","KIT","KOI","LAB","LAD","LAG","LAM","LAP","LAR","LAT",
        "LAV","LAW","LAX","LAY","LEA","LED","LEG","LEI","LET","LEW","LID","LIE","LIP","LIT","LOG","LOT","LOW","LYE",
        "MAC","MAD","MAL","MAN","MAP","MAR","MAT","MAW","MAY","MEL","MEN","MET","MHO","MID","MIL","MIX","MOB","MOD",
        "MOI","MOL","MON","MOO","MOP","MOR","MOT","MOW","MUD","MUG","NAB","NAE","NAG","NAP","NAW","NAY","NEB","NEE",
        "NEF","NET","NEW","NIB","NIL","NIM","NIP","NIT","NOB","NOD","NOG","NOM","NOR","NOT","NOW","NUB","NUN","NUT",
        "OAK","OAF","OAR","OAT","OCA","ODD","ODE","OFT","OHM","OOH","OPE","OPT","ORA","ORB","ORE","OUR","OUT","OVA",
        "OWE","OWL","OWN","PAD","PAH","PAL","PAN","PAP","PAR","PAS","PAT","PAW","PAX","PAY","PEA","PEG","PEN","PEP",
        "PET","PEW","PHI","PIE","PIG","PIN","PIP","PIT","PIU","PIX","PLY","POD","POI","POL","POM","POO","POP","POT",
        "POW","PRO","PRY","PSI","PUB","PUD","PUG","PUN","PUP","PUS","PUT","PYA","RAG","RAH","RAM","RAN","RAP","RAT",
        "RAW","RAY","REC","RED","REF","REI","REP","RES","RET","REV","REX","RHO","RIB","RID","RIG","RIM","RIP","ROB",
        "ROC","ROD","ROM","ROO","ROT","ROW","RUB","RUG","RUM","RUN","RUT","SAC","SAE","SAG","SAL","SAP","SAT","SAW",
        "SAY","SEA","SEC","SEG","SEN","SEP","SER","SET","SEW","SHE","SHY","SIP","SIR","SIT","SIX","SKA","SKI","SKY",
        "SLY","SOB","SOD","SOL","SOM","SON","SOP","SOT","SOV","SOW","SOX","SOY","SPA","SPY","SRI","STY","SUB","SUM",
        "SUN","SUQ","SUP","TAB","TAD","TAG","TAN","TAO","TAP","TAR","TAT","TAV","TAW","TAX","TAY","TEA","TEE","TEF",
        "TEG","TEL","TEN","THE","TIC","TIE","TIG","TIL","TIN","TIP","TOD","TOE","TOG","TOM","TON","TOO","TOP","TOR",
        "TOT","TOW","TOY","TUB","TUG","TUI","TUN","TUP","TUT","TWO","UDO","UGH","UKE","ULU","UMP","UNS","URN","USE",
        "UTE","VAT","VAV","VAW","VEE","VEX","VIA","VIE","VIM","VOW","VOX","WAD","WAG","WAN","WAP","WAR","WAS","WAX",
        "WAY","WEB","WED","WEE","WEN","WET","WHO","WHY","WIG","WIN","WIS","WIT","WIZ","WOE","WOG","WOK","WON","WOO",
        "WOP","WOW","YAK","YAM","YAP","YAW","YEA","YEP","YES","YET","YEW","YID","YIN","YOB","YOD","YOM","YON","YOU",
        "YOW","ZAG","ZAP","ZAX","ZED","ZEE","ZEK","ZEN","ZIG","ZIP","ZIT","ZOA","ZOO",
        // extra 3-letter words
        "ABY","ACY","ADZ","AFF","AGA","AHA","AID","AIT","ALB","ALS","ALY","AMB","AMO","ANA","AND","ANE","ANS","APT",
        "ARB","ARD","ARE","ARF","ARK","ARS","AUF","AUK","AVA","AVE","AYS","BAA","BAM","BEG","BEL","BIO","BIT","BOO",
        "BOT","BOW","BUB","BUS","CAL","CEP","CHI","COD","COG","DAG","DAP","DAW","DEF","DEL","DIN","DON","DOR","DUG",
        "DUN","DUP","DYE","EAU","EEK","ELS","EME","ERE","ERG","ERN","ERS","ESS","ETA","ETA","FAD","FAW","FEM","FEY",
        "GAB","GAE","GAP","GAR","GAW","GEL","GIE","GOB","GON","GOO","GOT","GUL","GUP","GUV","HAD","HAG","HAJ","HAS",
        "HAW","HAY","HEW","HOE","HOM","HUP","IMP","INK","JAK","JAP","JAT","JEW","JOE","JON","KAE","KAF","KAS","KAT",
        "LAP","LAS","LEB","LEX","LIG","LOO","LUG","LUM","MAK","MEW","MOC","NEB","NIM","NIX","NOX","OAF","OHO","OHS",
        "OOF","OWT","PAC","PEI","PEW","PIU","PLY","POH","PUD","PUL","PYE","RAN","RAS","RES","RIA","RIF","ROE","ROM",
        "RUE","SAG","SHH","SHY","SIN","SKY","SLY","SNY","SOD","STY","SUB","TAJ","TAP","TAS","TAT","TEP","TIS","TOD",
        "TON","TOP","TYE","UDO","UGH","UPO","UPS","UTE","VAR","VIG","WAE","WAN","WAP","WAS","WAW","WEE","WEM","WOD",
        "WYN","YOW","YUK","ZEP","ZOO",
        // 4-letter words
        "ABLE","ACES","ACHE","ACID","ACME","ACNE","ACRE","ACTS","ADZE","AFAR","AGAR","AGED","AGIO","AGOG","AGUE",
        "AIDE","AIDS","AIMS","AILS","AIRS","AIRY","AJAR","ALOE","ALSO","ALTO","ALUM","AMEN","AMID","AMOK","AMYL",
        "ANKH","ANON","APES","APEX","AQUA","ARCS","ARIA","ARMS","ARTY","ASHY","ATOP","AVID","AVOW","AXED","AXLE",
        "BAGS","BAKE","BALE","BALL","BAND","BANE","BANG","BARE","BARK","BARN","BARS","BASE","BASH","BASK","BATH",
        "BATS","BAYS","BEAD","BEAM","BEAN","BEAR","BEAT","BEDS","BEEN","BELL","BELT","BEND","BEST","BIAS","BIKE",
        "BILE","BILL","BIND","BITE","BLAB","BLOB","BLOC","BLOT","BLOW","BLUE","BLUR","BOAR","BOAT","BOLD","BOLT",
        "BOND","BONE","BOOK","BOOM","BOON","BOOR","BOOS","BOOT","BORE","BORN","BOSH","BOSS","BOTH","BOUT","BOXY",
        "BRAG","BRAN","BRAT","BREW","BRIG","BRIM","BRIT","BRUT","BUFF","BUGS","BULB","BULK","BULL","BUMP","BUNK",
        "BUNS","BUOY","BURN","BURP","BURR","BUSY","BUTT","BUZZ","BYES","CAFE","CAGE","CAGY","CAKE","CALL","CALM",
        "CAME","CAMP","CANE","CAPO","CAPE","CARD","CARE","CART","CASE","CASH","CAST","CAVE","CELL","CHAD","CHAT",
        "CHAW","CHEF","CHEW","CHIN","CHIP","CHOP","CHOW","CITE","CITY","CLAM","CLAP","CLAW","CLAY","CLEF","CLEW",
        "CLIP","CLOD","CLOG","CLOP","CLOT","CLUB","CLUE","COAL","COAT","COBS","COCO","COIF","COIL","COIN","COLA",
        "COLD","CODE","COKE","COLE","COME","CONE","CONK","COOK","COOL","COOP","COOT","COPE","COPY","CORD","CORE",
        "CORK","CORN","COST","COSY","COUP","COZY","COTS","COWS","CRAM","CRAW","CRIB","CROP","CROW","CUBE","CUFF",
        "CUPS","CURL","CZAR","DADO","DAIS","DALE","DAME","DAMP","DANK","DARE","DARK","DART","DATA","DATE","DAWN",
        "DAYS","DAZE","DEAD","DEAL","DEAN","DEAR","DEBT","DECK","DEED","DEEM","DEEP","DEFT","DELI","DELL","DENY",
        "DENT","DESK","DIET","DIKE","DILL","DIME","DING","DIRE","DIRT","DISC","DISH","DISK","DOCK","DOME","DONE",
        "DOOM","DOOR","DOPY","DOSE","DOTE","DOVE","DOWN","DOWL","DRAB","DRAG","DRAW","DRIP","DROP","DRUG","DRUM",
        "DUAL","DUNE","DUPE","DUSK","DUST","DUTY","EACH","EARL","EARN","EASE","EAST","EDGY","EDGE","EMIT","ENVY",
        "EPIC","EVEN","EVER","EVIL","EXAM","EXPO","FACE","FACT","FADE","FAIL","FAIR","FAKE","FALL","FAME","FANG",
        "FARE","FARM","FAST","FATE","FAWN","FAZE","FEAT","FEED","FEEL","FEET","FELL","FEND","FERN","FETE","FEUD",
        "FIEF","FIFE","FILE","FILL","FILM","FIND","FIRE","FIRM","FISH","FIST","FIZZ","FLAG","FLAP","FLAT","FLAW",
        "FLEA","FLED","FLEW","FLEX","FLIP","FLOG","FLOW","FLOE","FOAM","FOES","FOLD","FOLK","FOND","FONT","FOOD",
        "FOOL","FORD","FORE","FORK","FORM","FORT","FOUL","FOUR","FOWL","FOXY","FRAY","FREE","FROG","FROM","FUME",
        "FUND","FURL","FUSE","FUZZ","GALE","GANG","GASH","GATE","GAVE","GAWK","GAZE","GEAR","GELD","GERM","GIFT",
        "GILD","GILL","GIRD","GIRL","GIST","GIVE","GLAD","GLEE","GLEN","GLOB","GLOW","GLUE","GNAT","GNAW","GOAL",
        "GOLF","GOOD","GOOF","GORE","GORY","GOSH","GOUT","GOWN","GRAB","GRAM","GRAY","GREW","GRIN","GRIP","GRIT",
        "GUNK","GURU","GUST","HACK","HAIL","HAIR","HALE","HALF","HALL","HALO","HALT","HAND","HANK","HANG","HARD",
        "HARE","HARM","HARP","HASH","HATE","HAVE","HAWK","HAZE","HEAD","HEAL","HEAP","HEAR","HEAT","HEED","HEEL",
        "HELM","HELP","HEMP","HERB","HERD","HERO","HEWN","HIDE","HIGH","HILL","HILT","HIND","HINT","HIRE","HISS",
        "HOCK","HOER","HOLD","HOLE","HOME","HONE","HONK","HOOD","HOOK","HOOT","HOPE","HORN","HOSE","HOST","HOUR",
        "HULK","HULL","HUNG","HUNK","HUNT","HYMN","HYPO","IDEA","IDLE","IMAM","INCH","INFO","INKY","INTO","ISLE",
        "ITCH","ITEM","JACK","JADE","JAIL","JAPE","JEST","JIBE","JERK","JOIN","JOKE","JOLT","JOWL","JUNK","JUST",
        "KEEL","KEEN","KEEP","KENO","KERN","KIND","KING","KEYS","KIBE","KILT","KINE","KNOB","KNAP","KNEW","KNOT",
        "KOAN","KNOW","LACK","LACE","LADS","LAIN","LAIR","LAKE","LAMB","LAMP","LAND","LANE","LANK","LARK","LASH",
        "LASS","LAST","LATE","LATH","LAUD","LAVA","LAWN","LAZE","LAZY","LEAD","LEAF","LEAK","LEAN","LEAP","LEFT",
        "LEND","LESS","LEWD","LIFE","LIFT","LIKE","LIME","LIMP","LINE","LINK","LINT","LION","LISP","LIST","LIVE",
        "LOAD","LOAF","LOAN","LOBE","LOCK","LODE","LOFT","LOGO","LOIN","LONE","LONG","LOOK","LOOM","LOOP","LORD",
        "LORE","LOSE","LOSS","LOST","LOUD","LOVE","LUCK","LUAU","LUGE","LULL","LUMP","LUNG","LURK","LURE","LUST",
        "LYRE","MACE","MADE","MAIL","MAIN","MAKE","MALE","MALL","MANE","MAST","MATE","MAUL","MAYO","MAZE","MEAL",
        "MEAN","MEAD","MEAT","MEET","MELT","MEMO","MENU","MESA","MESS","MEWL","MICE","MIKE","MILD","MILE","MILK",
        "MILL","MINE","MINT","MINK","MINX","MIRE","MISS","MIST","MITT","MOAN","MOAT","MOCK","MODE","MOLD","MOLE",
        "MOPE","MORE","MOST","MOTH","MOUE","MOVE","MUCK","MULE","MULL","MUSE","MUSK","MUTT","MYTH","NAIL","NAME",
        "NARC","NAVY","NEAR","NEAT","NECK","NEED","NEWS","NEXT","NICE","NINE","NODE","NOME","NONE","NOEL","NOOK",
        "NOON","NOPE","NORM","NOSE","NOSH","NOTE","NOUN","NOVA","NUDE","NUKE","NUMB","OAFS","OATH","OBEY","OBOE",
        "ODDS","OKAY","OKRA","OMEN","OMIT","ONCE","ONLY","ONYX","OPEN","OVAL","OVEN","OVER","OXEN","PACE","PACK",
        "PAGE","PAID","PAIN","PALE","PALM","PANT","PAPA","PARA","PARE","PARK","PAST","PATH","PAVE","PEAK","PEAL",
        "PEAR","PEAT","PEEK","PEEL","PEER","PEST","PHON","PICK","PIED","PIER","PILE","PIKE","PILL","PINE","PINK",
        "PIPE","PLAN","PLAY","PLEA","PLOD","PLOT","PLOW","PLUG","PLUM","PLUS","POCK","POEM","POET","POLE","POLL",
        "POOL","POOR","POPE","PORE","PORK","PORT","POSE","POUR","PRAY","PREP","PREY","PRIM","PROD","PROP","PROW",
        "PUCE","PUFF","PULL","PULP","PUMP","PUNK","PUNY","PURE","PUSH","RACE","RACK","RAGA","RAGE","RAFF","RAIL",
        "RAIN","RAKE","RAMP","RANG","RANK","RANT","RASH","RATE","READ","REAL","REAP","REAM","REDO","REED","REEF",
        "REEK","REEL","RELY","REND","RENT","RICH","RIDE","RIFT","RILE","RING","RIOT","RISE","RISK","ROAD","ROAM",
        "ROAR","ROBE","RODE","ROIL","ROLE","ROLL","ROOF","ROOM","ROOT","ROPE","ROSE","ROUT","ROVE","RUDE","RUIN",
        "RULE","RUSH","RUSE","RUST","RUTH","SAGA","SAGO","SAGE","SAID","SAIL","SALE","SAKI","SALT","SAME","SAND",
        "SANE","SANG","SANK","SARI","SASH","SAVE","SCAN","SCAR","SEAL","SEAM","SEED","SEEP","SEEM","SEEN","SELF",
        "SELL","SEND","SENT","SERE","SEWN","SHAG","SHAW","SHED","SHIM","SHIN","SHIP","SHIV","SHMO","SHOD","SHOE",
        "SHOP","SHOT","SHOW","SHUN","SHUT","SICK","SIGN","SILK","SILL","SING","SINK","SIZE","SKIN","SKIP","SLAB",
        "SLAM","SLAP","SLID","SLIM","SLIP","SLOB","SLOE","SLOG","SLOT","SLOW","SLUG","SLUM","SLOP","SLUR","SMEW",
        "SMUG","SNAG","SNAP","SNOB","SNOW","SNUB","SNUG","SOAP","SOCK","SOFT","SOIL","SOLE","SOMA","SOME","SONG",
        "SOON","SORE","SORT","SOUL","SOUP","SOUR","SPAN","SPAR","SPEC","SPEW","SPIN","SPIT","SPOT","SPUD","SPUR",
        "STAB","STAG","STAR","STAY","STEM","STEP","STEW","STIR","STOP","STOW","STUB","STUD","STYE","SUCK","SUED",
        "SULK","SUMO","SUNG","SUNK","SURF","SWAB","SWAM","SWAN","SWAP","SWAT","SWIM","SWUM","TACK","TAEL","TALE",
        "TALK","TALL","TAME","TAMP","TAPE","TARN","TARP","TAUT","TEAK","TEAM","TEAR","TEEM","TELL","TEND","TERM",
        "TEST","THAN","THAT","THEM","THEN","THEY","THIN","THIS","TILE","TILL","TILT","TIME","TINY","TIRE","TOAD",
        "TOLD","TOLL","TOMB","TOME","TONG","TORC","TORE","TORN","TORT","TOUR","TRAM","TRAP","TRIM","TRIO","TRIP",
        "TROD","TROT","TRUE","TSAR","TUBE","TUFT","TUNE","TURF","TUSK","TUTU","TWIN","TWIG","TWIT","TYPE","TYKE",
        "UGLY","UDOS","UMPH","UNDO","UNIT","UNTO","UPON","URGE","USED","VAMP","VALE","VANE","VASE","VAST","VEAL",
        "VEIL","VEIN","VERY","VEST","VETO","VIBE","VIED","VILE","VINE","VISA","VISE","VITA","VOID","VOLT","VOTE",
        "WADE","WAIF","WAGE","WAIL","WAIT","WAKE","WALK","WALL","WANE","WANT","WARD","WARM","WARN","WARP","WART",
        "WARY","WASP","WAVE","WEAK","WEAL","WEAN","WEAR","WEED","WEEK","WEEP","WEFT","WELL","WEND","WENT","WERE",
        "WEST","WHAM","WHAT","WHEN","WHET","WHIP","WHIR","WHIZ","WIDE","WIFE","WILD","WILE","WILL","WILT","WIND",
        "WINE","WING","WIRY","WIRE","WISE","WISH","WITH","WOAD","WOLF","WOOD","WOOL","WORD","WORE","WORM","WORN",
        "WOVE","WREN","WRIT","YARD","YARN","YEAR","YELL","YOGA","YOLK","YOUR","YORE","YUCK","YULE","ZEAL","ZERO",
        "ZEST","ZINC","ZONE",
        // 4-letter words: systematic CVC patterns
        "ABUT","ACTS","AEON","AFAR","AGED","AGUE","AIDE","AIRY","AMOK","ANEW","APEX","AQUA","ARCH","ARIA","ARID",
        "ARTY","ASHY","ATOP","AVID","AWRY","AXED","AXLE","BAGS","BALD","BALK","BALM","BARD","BARM","BARB","BASS",
        "BAWD","BAWL","BEAN","BIER","BIFF","BILE","BILK","BLOB","BLOC","BONG","BONK","BOOM","BOON","BOOR","BOSH",
        "BOSS","BOXY","BRIG","BRIM","BRIT","BROW","BUBO","BUCK","BUFF","BULB","BULL","BURL","BURP","BUZZ","CAFE",
        "CALF","CALK","CALX","CAMO","CAPO","CARB","CARP","CHAW","CHEF","CHEW","CHIN","CHOP","CHOW","CHIC","CLEF",
        "CLEW","COBS","COCO","COIF","COLA","COMA","CONE","CONK","COOF","COOP","COOT","COPY","CORF","COSH","COZY",
        "CRAM","CRAW","CRUX","CUFF","CZAR","DADO","DACE","DAIS","DALE","DAME","DAMN","DANK","DAPS","DASH","DAUB",
        "DECO","DEFT","DELI","DELL","DEMY","DENT","DERM","DERV","DHAL","DHOW","DIGS","DILL","DING","DINT","DIRL",
        "DISC","DITZ","DOJO","DORK","DORY","DOSS","DUFF","DULY","DUNG","DUNK","DURA","EARL","EARN","EDGY","ELAN",
        "EMIT","ENVY","ERGO","ETCH","EVEN","EVIL","EXEC","EXPO","FAIN","FLAY","FLEE","FLIC","FLIT","FLOE","FLOP",
        "FLUX","FOND","FOIL","GENT","GLUT","GOBY","GONK","GOOF","GORE","GORY","GOSH","GOUT","GUFF","GULF","GULP",
        "HACK","HAFT","HALO","HANK","HEEP","HEFT","HEWN","HIGH","HILT","HIND","HINT","HISS","HOCK","HOER","HOGS",
        "HONE","HONK","HOOT","HORN","IBIS","ICON","IMPS","INCH","INFO","INKY","ISLE","ITCH","ITEM","JAZZ","JIBE",
        "JILT","JINX","JIVE","JOSS","JOWL","KEEN","KENO","KERN","KEYS","KIBE","KILT","KINE","KNAP","KNEW","KOAN",
        "LACK","LADS","LAIN","LAIR","LANK","LATH","LAUD","LAZE","LAZY","LEAK","LEEK","LEET","LEWD","LIMB","LIMP",
        "LIND","LINT","LISP","LOBE","LOCH","LOFT","LOGO","LOIN","LOUR","LOUT","LUAU","LUGE","LYAM","LYRE","MACE",
        "MAUL","MAYO","MESA","MEWL","MILD","MINK","MINX","MITT","MOAT","MOUE","NARK","NARY","NAVE","NEWT","NIGH",
        "NIMB","NOEL","NOOK","NOUN","NOVA","NUKE","OBOE","OKAY","OKRA","OMIT","OPUS","ORCA","OWED","PACT","PAPA",
        "PARA","PASH","PAWN","PHAT","PIER","PIKA","POCK","PONG","PONT","POOH","POSH","POUT","PUCE","RAGA","RAFF",
        "REIN","RELY","REND","REVS","RIMY","RINK","ROVE","RUNE","RYOT","SCAB","SCAD","SCAM","SERE","SEWN","SHAG",
        "SHAW","SHIM","SHIV","SHMO","SHOD","SNAG","SOMA","SPEW","SPUD","STOB","STOW","STYE","SUMO","SWAB","SWAM",
        "SWAN","SWUM","TAEL","TAMP","TANG","TARN","TARP","TIER","TIFF","TIKE","TORC","TREK","TRIM","TSAR","TUTU",
        "TWIG","TWIT","TYKE","UMPH","VAMP","VIED","VIMY","VISE","VITA","WAIF","WALE","WAND","WICK","WILE","WOAD",
        "YORE","YUCK","YULE","WOVE","WREN","WRIT","UNDO","UNIT","UPON","URGE","VALE","VEIL","VEIN","VEST","VETO",
        // more 4-letter patterns
        "ABLY","AHEM","AJAR","ALMS","AMBO","AMPS","ANEW","ANTA","ANTE","ANTI","ANUS","AWRY","BONG","BONK","BROW",
        "CAFE","CARB","CARP","CODA","COMA","CUSP","DACE","DANG","DECO","DEMY","FAIN","FLAY","FLEE","FLOP","FLUX",
        "GUFF","GULF","GULP","HACK","HEFT","IBIS","ICON","IMPS","JAZZ","JILT","JINX","JIVE","JOSS","KELP","KICK",
        "KILL","KINK","KILN","KNIT","LARD","LEES","LENS","LEVY","LICK","LIMB","LOCH","LOUR","LOUT","MALT","MANA",
        "MARK","MARL","MARS","MELD","MESH","MOIL","MOXA","NARK","NARY","NAVE","PHAT","PIER","PIKA","PONG","PONT",
        "POOH","POSH","POUT","REIN","RIMY","RINK","RUNE","RYOT","SCAB","SCAD","SCAM","SLAG","SLOB","SLOG","SLOP",
        "SLUR","SNAG","SOMA","SPEW","SPUD","STOB","STOW","STYE","SUMO","SWAB","SWAM","SWAN","SWUM","TAMP","TANG",
        "TARN","TARP","TIER","TIFF","TIKE","TREK","TSAR","TUTU","TWIG","TWIT","TYKE","UMPH","VAMP","VIMY","VISE",
        "VITA","WAIF","WALE","WAND","WICK","WILE","WOAD","YORE","YUCK","YULE","WOVE","WREN","WRIT",
        // 4-letter words: common short words often missed
        "ABET","ABUT","AEON","AFAR","AGAR","AGED","AGUE","AIDE","AIRY","ALOE","ALTO","ALUM","AMOK","ANEW","ANKH",
        "ANON","AQUA","ARCS","ARIA","ARTY","ASHY","ATOP","AVID","AVOW","AXED","AXLE","BAGS","BALD","BALK","BALM",
        "BARD","BARM","BARB","BASS","BAWD","BAWL","BIER","BIFF","BILK","BLOB","BLOC","BONG","BONK","BOOR","BOSH",
        "BOSS","BOXY","BRIG","BRIM","BRIT","BROW","BUBO","BUCK","BUFF","BULB","BURL","BURP","BUZZ","CAFE","CALF",
        "CALK","CALX","CAMO","CAPO","CARB","CARP","CHAW","CHEF","CHEW","CHIN","CHOP","CHOW","CHIC","CLEF","CLEW",
        "COCO","COIF","COLA","COMA","COOF","COOP","COOT","COPY","CORF","COSH","COZY","CRAM","CRAW","CRUX","CUFF",
        "CZAR","DADO","DAIS","DAME","DAMN","DANK","DAPS","DASH","DAUB","DECO","DEFT","DELI","DELL","DEMY","DENT",
        "DERM","DERV","DHAL","DHOW","DILL","DING","DINT","DIRL","DISC","DITZ","DOJO","DORK","DORY","DOSS","DUFF",
        "DUNG","DUNK","DURA","ELAN","ERGO","ETCH","EXEC","EXPO","FLAY","FLEE","FLIC","FLIT","FLOP","FLUX","FOIL",
        "GENT","GLUT","GOBY","GONK","GUFF","GULF","GULP","HAFT","HANK","HEFT","HEWN","HOCK","HOER","IBIS","ICON",
        "JAZZ","JIBE","JILT","JINX","JIVE","JOSS","JOWL","KENO","KIBE","KINE","KNAP","KNEW","KOAN","LANK","LATH",
        "LAUD","LAZE","LAZY","LEET","LEWD","LIMB","LIMP","LINT","LISP","LOBE","LOCH","LOFT","LOGO","LOUR","LOUT",
        "LUAU","LUGE","LYAM","LYRE","MAUL","MAYO","MESA","MEWL","MILD","MINK","MINX","MITT","MOUE","NAVE","NEWT",
        "NIGH","NIMB","NOEL","NOUN","NOVA","NUKE","OBOE","OKAY","OKRA","OPUS","ORCA","OWED","PACT","PAPA","PARA",
        "PASH","PAWN","PIER","PIKA","POCK","PONT","POOH","POSH","POUT","PUCE","RAGA","RAFF","RIMY","RINK","RUNE",
        "RYOT","SERE","SEWN","SHAG","SHAW","SHIM","SHIV","SHMO","SHOD","SOMA","SPUD","STOB","STOW","STYE","SWAB",
        "SWAM","SWAN","SWUM","TAEL","TAMP","TARN","TARP","TIER","TIFF","TIKE","TORC","TREK","TSAR","TUTU","TWIG",
        "TWIT","TYKE","UMPH","VAMP","VIMY","VISE","VITA","WAIF","WALE","WAND","WICK","WILE","WOAD","YUCK","YULE",
        // CVC+E words (4-letter)
        "ABLY","AFAR","AHEM","AJAR","ALMS","AMBO","AMPS","ANEW","ANTA","ANTE","ANTI","ANUS","ARCH","ARIA","ARID",
        "AWRY","BALD","BALK","BALM","BARD","BARM","BAWD","BIER","BIFF","BILK","BONG","BONK","BROW","BUBO","BUCK",
        "BURL","CAFE","CALF","CALK","CALX","CAMO","CARB","CARP","CHIC","CODA","COMA","CORF","COSH","CUSK","CUSP",
        "DACE","DAMN","DANK","DAPS","DAUB","DECO","DEMY","DERM","DERV","DHAL","DHOW","DINT","DIRL","DITZ","DOJO",
        "DORK","DORY","DOSS","DUFF","DUNG","DUNK","DURA","ELAN","ETCH","FAIN","FLAY","FLEE","FLIC","FLIT","FLOP",
        "FLUX","FOND","FOIL","GENT","GLUT","GOBY","GONK","GUFF","GULF","GULP","HACK","HEFT","HOGS","IBIS","ICON",
        "IMPS","JAZZ","JILT","JINX","JIVE","JOSS","KELP","KICK","KILL","KINK","KILN","KNIT","LARD","LEEK","LEES",
        "LENS","LEVY","LICK","LIMB","LOCH","LOUR","LOUT","LYAM","MALT","MANA","MARE","MARK","MARL","MARS","MELD",
        "MESH","MILD","MOIL","MOXA","NARK","NARY","NAVE","NEWT","NIGH","NIMB","NOUN","NUKE","PACT","PASH","PAWN",
        "PHAT","PIER","PIKA","PONG","PONT","POOH","POSH","POUT","REIN","RELY","REND","REVS","RIMY","RINK","RUNE",
        "RYOT","SCAB","SCAD","SCAM","SLAB","STOB","TANG","TIKE","TOSS","TREK","VAMP","WALE","WAND","WICK","WILE",
        "YORE","NETT","PUTT","MITT","BUTT","MUTT","WATT","DITT","HITT","BITT","GELT","BELT","FELT","MELT","PELT",
        "WELT","BOLT","COLT","DOLT","JOLT","MOLT","VOLT","HOLT","HARK","BARK","DARK","LARK","MARK","PARK","NARK",
        "RARK","WARK","DUSK","MUSK","RUSK","TUSK","BUNK","DUNK","FUNK","GUNK","HUNK","JUNK","PUNK","SUNK","DUNG",
        "HUNG","LUNG","RUNG","SUNG","BURG","FURL","CURL","GIRL","EARL","PERL","HURL","CHURN","BURN","TURN","FERN",
        "TERN","KERN","HERL","MERL","BERM","GERM","PERM","TERM","WORM","FORM","NORM","DORM","FORD","CORD","LORD",
        "WORD","BORE","CORE","FORE","GORE","MORE","PORE","SORE","TORE","WORE","YORE","BORE","DOTE","NOTE","VOTE",
        "MOTE","ROTE","TOTE","COKE","JOKE","POKE","WOKE","YOKE","BONE","CONE","DONE","GONE","HONE","LONE","NONE",
        "TONE","ZONE","DOME","FOAM","ROAM","LOAM","SOAM","GOAM","BOMB","COMB","TOMB","WOMB","FOND","BOND","POND",
        "WAND","BAND","HAND","LAND","SAND","FEND","BEND","LEND","MEND","REND","SEND","TEND","WEND","WIND","FIND",
        "BIND","KIND","MIND","RIND","FOND","BOND","POND","WAND","FUND","BIND","HIND","DINE","FINE","LINE","MINE",
        "PINE","VINE","WINE","NINE","CITE","BITE","KITE","MITE","SITE","LITE","FIRE","HIRE","TIRE","WIRE","DIRE",
        "SIRE","BILE","FILE","MILE","PILE","RILE","TILE","VILE","WILE","AILE","BIKE","DIKE","HIKE","LIKE","MIKE",
        "PIKE","TIKE","AIDE","BIDE","HIDE","RIDE","SIDE","TIDE","WIDE","CAGE","MAGE","RAGE","SAGE","WAGE","PAGE",
        "BAKE","CAKE","FAKE","LAKE","MAKE","RAKE","SAKE","TAKE","WAKE","BALE","DALE","GALE","HALE","MALE","PALE",
        "SALE","TALE","VALE","BANE","CANE","JANE","LANE","MANE","PANE","SANE","VANE","WANE","BALE","DARE","FARE",
        "HARE","BARE","CARE","MARE","PARE","RARE","WARE","DATE","FATE","GATE","LATE","MATE","RATE","SATE","CAVE",
        "GAVE","HAVE","NAVE","PAVE","RAVE","SAVE","WAVE","FACE","LACE","MACE","PACE","RACE","BRACE","BASE","CASE",
        // CVC+E words (4-letter)
        "BODE","BOLE","COTE","COVE","DOLE","DUDE","GIBE","GLEE","HOVE","HUGE","HYPE","JAKE","JAPE","JIBE","JUNE",
        "KALE","LAZE","LITE","LUBE","LUNE","LUTE","MIME","MOTE","MUTE","NOME","NOTE","NUDE","OGLE","PAVE","PIKE",
        "POKE","RAVE","RIFE","RIME","ROTE","ROVE","RUDE","RUSE","SAKE","SITE","SLOE","TOTE","TUBE","VICE","VOLE",
        "WADE","WOKE","YOKE",
        // 4-letter plurals / inflections
        "ACES","ACTS","AGES","AIDS","AIMS","AILS","AIRS","ANTS","APES","ARCS","ARMS","ARTS","AXES","BAGS","BARS",
        "BATS","BAYS","BEDS","BIDS","BITS","BOWS","BOYS","BUGS","BUNS","BYES","CABS","CANS","CAPS","CARS","CATS",
        "COBS","COPS","COTS","COWS","CUBS","CUPS","CUTS","DADS","DAMS","DAYS","DENS","DIGS","DIMS","DIPS","DOCS",
        "DOES","DOGS","DOTS","DUES","DYES","EARS","EGGS","EELS","ELMS","EYES","FANS","FATS","FIGS","FINS","FOES",
        "FOGS","FURS","GELS","GEMS","GIGS","GODS","GUMS","GUNS","GUTS","GUYS","HAMS","HATS","HENS","HITS","HUBS",
        "HUGS","HUTS","ICES","IDES","IRES","JABS","JAMS","JARS","JAWS","JETS","JOES","JOBS","JOGS","JOTS","JUGS",
        "KEGS","KITS","LABS","LADS","LAPS","LAWS","LEGS","LIDS","LIPS","LOGS","LOTS","LYES","MAPS","MATS","MOBS",
        "MOPS","MUGS","NAPS","NETS","NIPS","NODS","NUTS","OARS","OATS","ODES","ORBS","ORES","OWES","PADS","PANS",
        "PARS","PATS","PAWS","PEAS","PEGS","PENS","PETS","PIES","PIGS","PINS","PITS","PODS","PUNS","PUPS","RAGS",
        "RAMS","RAPS","RATS","RAYS","RIBS","RODS","RUBS","RUGS","RUTS","SAPS","SAWS","SEAS","SETS","SEWS","SIPS",
        "TABS","TAGS","TANS","TAPS","TARS","TEAS","TIES","TINS","TIPS","TOES","TONS","TOPS","TOTS","TOYS","TUBS",
        "TUGS","URNS","VATS","VOWS","WADS","WARS","WIGS","WOES","ROES","RUES",
        // 5-letter words
        "ABOUT","ABOVE","ABUSE","ACTOR","ACUTE","ADMIT","ADOPT","ADULT","AFTER","AGAIN","AGENT","AGREE","AHEAD",
        "ALARM","ALBUM","ALERT","ALIKE","ALIGN","ALIVE","ALOFT","ALONE","ALONG","ALOUD","ALTER","AMBER","AMBLE",
        "AMEND","ANGEL","ANGER","ANGLE","ANGRY","ANIME","ANNEX","ANTIC","APART","APPLE","APPLY","ARENA","ARGUE",
        "ARISE","ARMOR","AROMA","ARRAY","ASIDE","ASSET","AUDIO","AUDIT","AVOID","AWAKE","AWARD","AWARE","AWFUL",
        "BADGE","BARGE","BASIC","BASIN","BASIS","BATCH","BEACH","BEARD","BEAST","BEGAN","BEGIN","BEING","BELOW",
        "BENCH","BILLY","BINGO","BIRCH","BIRTH","BISON","BLAND","BLANK","BLAST","BLAZE","BLEAK","BLEED","BLEND",
        "BLESS","BLIND","BLOCK","BLOOD","BLOOM","BLOWN","BLUNT","BOARD","BOAST","BOUND","BRACE","BRAIN","BRAND",
        "BRAVE","BREAK","BREED","BRICK","BRIDE","BRIEF","BRINE","BRINK","BROKE","BROOD","BROTH","BROWN","BULLY",
        "BURLY","BUYER","CABIN","CAMEL","CANDY","CARRY","CATCH","CAUSE","CEDAR","CHAIN","CHALK","CHAMP","CHAOS",
        "CHARM","CHEAT","CHEEK","CHEER","CHESS","CHEST","CHIEF","CHILD","CHILI","CHIME","CHIMP","CHINA","CHORD",
        "CHUNK","CIVIC","CIVIL","CLAIM","CLAMP","CLANK","CLASH","CLASP","CLASS","CLEAT","CLERK","CLICK","CLIMB",
        "CLING","CLOAK","CLOCK","CLONE","CLOSE","CLOTH","CLOUD","CLOWN","COACH","COBRA","COCOA","COLOR","COMET",
        "CORAL","COUNT","COURT","COVER","CRACK","CRAFT","CRAMP","CRANE","CRASH","CRAWL","CREAK","CREAM","CREEK",
        "CREEP","CREST","CRIME","CRISP","CROSS","CROWD","CROWN","CRUEL","CRUSH","CRUST","CRYPT","CURRY","CURSE",
        "CURVE","CYCLE","DAILY","DAISY","DANCE","DEPTH","DERBY","DIRTY","DITCH","DIVER","DIZZY","DODGE","DOING",
        "DONOR","DOUBT","DOUGH","DRAIN","DRAPE","DREAD","DREAM","DRESS","DRIED","DRIFT","DRILL","DRINK","DRIVE",
        "DRONE","DROOL","DROVE","DRUNK","DRYER","DYING","EAGLE","EARLY","EARTH","EATEN","EIGHT","ELITE","EMPTY",
        "ENEMY","ENJOY","ENTER","ENTRY","EQUAL","EVENT","EVERY","EXACT","EXIST","EXTRA","FABLE","FACET","FAIRY",
        "FAITH","FANCY","FATAL","FEAST","FEVER","FIBER","FIELD","FIEND","FIFTH","FIFTY","FIGHT","FINAL","FIXED",
        "FLAIR","FLAME","FLARE","FLASH","FLASK","FLESH","FLICK","FLIES","FLING","FLOAT","FLOCK","FLOOD","FLOOR",
        "FLOSS","FLUFF","FLUNK","FLUSH","FOCAL","FOGGY","FORAY","FORCE","FORGE","FORTE","FORUM","FOUND","FRAME",
        "FRANK","FREED","FRESH","FRONT","FROST","FROZE","FULLY","FUNNY","GAMES","GHOST","GIRTH","GIVEN","GLAND",
        "GLARE","GLASS","GLEAM","GLOBE","GLORY","GLOSS","GLOVE","GOING","GRACE","GRADE","GRAIN","GRAND","GRANT",
        "GRAPE","GRASP","GRASS","GRATE","GRAVE","GRAVY","GRAZE","GREED","GREET","GRIEF","GRIND","GROAN","GROIN",
        "GROPE","GROSS","GROUT","GROVE","GROWL","GRUFF","GUARD","GUILD","GUILE","GUILT","GUSTO","HABIT","HAPPY",
        "HARSH","HAVEN","HEDGE","HEIST","HENCE","HOARD","HOLLY","HOMER","HONEY","HONOR","HORSE","HOTEL","HOUSE",
        "HUMAN","HUMOR","HURRY","HUSKY","IMAGE","IMPLY","INDEX","INNER","INPUT","INTER","INTRO","ISSUE","IVORY",
        "JELLY","JEWEL","JUMBO","JUICE","JUICY","KARMA","KAYAK","KNIFE","KNOCK","LABEL","LANCE","LANKY","LAPSE",
        "LARGE","LASER","LATER","LAUGH","LAYER","LEARN","LEASE","LEAST","LEAVE","LEGAL","LEMON","LIGHT","LIMIT",
        "LINER","LIVER","LOCAL","LODGE","LOGIC","LOOSE","LOVER","LOWER","LOYAL","LUNAR","LUSTY","LYRIC","MAGIC",
        "MAJOR","MANOR","MAPLE","MARCH","MARSH","MATCH","MAYOR","MEDIA","MERCY","MERIT","METAL","MIGHT","MINOR",
        "MINUS","MIRTH","MOIST","MONEY","MONTH","MORAL","MOUTH","MOVIE","MUDDY","MUSIC","NAIVE","NERVE","NEVER",
        "NIGHT","NOBLE","NOISE","NORTH","NOTCH","NOVEL","NURSE","NYMPH","OCEAN","OFFER","OLIVE","ONSET","ORDER",
        "OTHER","OUTER","OWNER","OXIDE","OZONE","PAINT","PAPER","PARTY","PASTA","PATCH","PEARL","PENAL","PERCH",
        "PHOTO","PIANO","PIECE","PILOT","PINCH","PITCH","PIXEL","PIXIE","PLACE","PLAIN","PLANE","PLANK","PLANT",
        "PLATE","PLAZA","PLEAD","PLEAT","PLUCK","PLUMB","PLUME","PLUMP","PLUNK","POINT","POLAR","POPPY","POWER",
        "PRESS","PRICE","PRIDE","PRIME","PRINT","PRIOR","PRIZE","PROBE","PROOF","PROSE","PROUD","PROVE","PROWL",
        "PULSE","PUNCH","PUPIL","PURSE","QUEEN","QUERY","QUEST","QUICK","QUIET","QUOTA","QUOTE","RADAR","RADIO",
        "RAISE","RANCH","RANGE","RAPID","RATIO","REACH","REACT","READY","REALM","REBUT","REIGN","RELAX","REPAY",
        "REPLY","RIGHT","RIGID","RISKY","RIVAL","RIVER","RIVET","ROBOT","ROCKY","ROUGE","ROUGH","ROUND","ROUTE",
        "ROWDY","RULER","RURAL","RUSTY","SADLY","SAINT","SAUCE","SCALE","SCALP","SCAMP","SCANT","SCARF","SCENE",
        "SCENT","SCONE","SCOOP","SCOPE","SCORE","SCOUT","SCOWL","SCRAM","SCRAP","SCRUB","SEIZE","SENSE","SEVEN",
        "SHADE","SHAKE","SHALL","SHAME","SHAPE","SHARE","SHARP","SHEER","SHONE","SHORE","SHOUT","SHOVE","SHRUB",
        "SIEGE","SINCE","SIXTH","SIXTY","SKILL","SKIRT","SKULL","SLACK","SLAIN","SLANT","SLASH","SLATE","SLAVE",
        "SLEEK","SLEEP","SLEET","SLICK","SLIDE","SLING","SLOPE","SMART","SMASH","SMELL","SMELT","SMILE","SMITE",
        "SMOKE","SNACK","SNAIL","SNAKE","SNARE","SNIFF","SNORE","SOLAR","SOLID","SOUTH","SPACE","SPARK","SPAWN",
        "SPEAK","SPEAR","SPEED","SPEND","SPICE","SPINE","SPLAT","SPOKE","SPOON","SPRAY","SQUAD","STACK","STAFF",
        "STAGE","STAIN","STAIR","STAKE","STALE","STALL","STAMP","STAND","STARK","START","STASH","STATE","STEAM",
        "STEEL","STEEP","STEER","STERN","STICK","STIFF","STILL","STOCK","STONE","STOOD","STORM","STORY","STOUT",
        "STOVE","STRAP","STRAY","STRUM","STUCK","STUDY","STUFF","STUMP","STUNG","STYLE","SUGAR","SUITE","SUNNY",
        "SUPER","SURGE","SWEAR","SWEEP","SWEET","SWEPT","SWIFT","SWING","SWIPE","SWOOP","SWORD","TABLE","TASTE",
        "TAUNT","THORN","THREE","TIGER","TIMER","TIRED","TITLE","TOAST","TOKEN","TORCH","TOTAL","TOUCH","TOUGH",
        "TOWER","TOXIC","TRACE","TRACK","TRADE","TRAIL","TRAIN","TRAMP","TREAD","TREND","TRIBE","TRICK","TRIED",
        "TROOP","TRUCK","TRULY","TRUMP","TRUNK","TRUST","TRUTH","TULIP","TUMOR","TUNIC","UNION","UNITY","UNTIL",
        "UPPER","USAGE","UTTER","VAGUE","VALID","VAULT","VIGOR","VIRAL","VISIT","VISTA","VITAL","VIVID","VOCAL",
        "VOICE","VOUCH","WALTZ","WASTE","WATCH","WATER","WEARY","WEAVE","WEDGE","WEIGH","WEIRD","WHALE","WHEAT",
        "WHEEL","WHERE","WHICH","WHILE","WHITE","WHOLE","WHOSE","WIELD","WINDY","WITCH","WOMAN","WOMEN","WOOZY",
        "WORLD","WORRY","WORSE","WORST","WORTH","WOULD","WRATH","WRECK","WROTE","YOUNG","YOUTH","ZIPPY",
        // -ER words (5-letter)
        "BAKER","BIKER","BITER","CAPER","CARER","CATER","CAVER","CIDER","CITER","DINER","DIVER","DOTER","FAKER",
        "FARER","FIVER","GAMER","GAPER","GAZER","GIVER","HATER","HIDER","HIKER","HIRER","JOKER","LATER","LIFER",
        "LIKER","LIMER","LINER","LITER","LIVER","LOSER","LOVER","MAKER","MASER","MATER","MINER","MISER","MITER",
        "MOVER","MUTER","NOTER","OATER","OGLER","PALER","PAVER","PIKER","PIPER","POKER","POLER","PORER","RACER",
        "RAKER","RATER","RAVER","RIDER","RIPER","RISER","ROPER","ROVER","RULER","SANER","SAVER","SIREN","SIZER",
        "SKIER","TAKER","TAMER","TAPER","TIMER","TOKER","TONER","TOTER","TUNER","VIPER","VOTER","WADER","WAGER",
        "WAVER","WIDER","WIPER","WISER","YOKER",
        // -ED words (5-letter)
        "BAKED","BIKED","BORED","CAGED","CAKED","CANED","CAPED","CARED","CASED","CAVED","CITED","CODED","COKED",
        "CONED","COPED","CORED","DARED","DATED","DAZED","DIKED","DIMED","DINED","DOZED","DUPED","FACED","FADED",
        "FAKED","FARED","FATED","FAZED","FILED","FINED","FIRED","FUMED","FUSED","GAMED","GAZED","GIBED","GIVEN",
        "HALED","HAZED","HIKED","HIRED","HOPED","HOSED","HYPED","JOKED","KITED","LACED","LAKED","LAVED","LAZED",
        "LIKED","LIMED","LINED","LIVED","LOVED","LURED","MATED","MAZED","MINED","MIRED","MOPED","MOVED","MUTED",
        "NAMED","NOTED","PACED","PAVED","PIKED","PILED","PINED","PIPED","POKED","POSED","RACED","RAKED","RATED",
        "RAVED","RAZED","RILED","RIMED","ROBED","ROPED","ROVED","RULED","SAGED","SAVED","SITED","SIZED","TIMED",
        "TIRED","TONED","TOTED","TUNED","TYPED","VOTED","WADED","WAGED","WAVED","WIPED","WIRED","ZONED",
        // -ES/-S plurals of 4-letter base words (5-letter)
        "BAKES","BIKES","BITES","BODES","BONES","BORES","CAKES","CANES","CAPES","CARES","CASES","CAVES","CITES",
        "CODES","COKES","CONES","CORES","DATES","DIMES","DINES","DOLES","DOMES","DOSES","DOTES","DUNES","FACES",
        "FADES","FAKES","FARES","FATES","FILES","FINES","FIRES","FUMES","FUSES","GALES","GAMES","GATES","GAZES",
        "HIDES","HIKES","HIRES","HOLES","HOMES","HOPES","HOSES","JOKES","LANES","LIMES","LINES","LITES","LIVES",
        "LODES","LORES","LOVES","LUBES","LUTES","MAKES","MALES","MANES","MATES","MAZES","MILES","MINES","MIRES",
        "MITES","MODES","MOLES","MOPES","MOVES","MULES","MUTES","NAMES","NODES","NOTES","PACES","PAVES","PILES",
        "PINES","PIPES","POKES","POLES","POSES","RACES","RAKES","RATES","RAVES","RIDES","ROBES","ROLES","ROPES",
        "ROSES","RULES","RUSES","SAGES","SALES","SAVES","SITES","SIZES","TALES","TAPES","TILES","TIMES","TIRES",
        "TOMES","TONES","TOTES","TUBES","TUNES","TYPES","VANES","VASES","VINES","VOTES","WAVES","WINES","ZONES",
        // additional 5-letter words
        "ABACK","ABASH","ABATE","ABBEY","ABBOT","ABIDE","ABODE","ABORT","ACORN","ACRID","ADAGE","ADEPT","ADOBE",
        "AFOOT","AGAVE","AGILE","AGLOW","AGONY","AGORA","ALGAE","ALLAY","ALLOT","ALOOF","ALTAR","AMASS","AMAZE",
        "AMISS","ANNOY","ANVIL","APHID","APRON","APTLY","ARBOR","ARDOR","ARGOT","ARTSY","ASCOT","ASKEW","ATOLL",
        "ATONE","ATTIC","AWASH","BADLY","BAGEL","BAGGY","BAIZE","BALMY","BANDY","BANJO","BARON","BASIL","BASTE",
        "BATTY","BAYOU","BEADY","BEEFY","BELIE","BELLE","BEZEL","BILGE","BITTY","BLARE","BLIMP","BLISS","BLOAT",
        "BODGE","BOGUS","BOSSY","BOXER","BRAWL","BRAWN","BRAZE","BREAM","BRINE","BRISK","BROIL","BUDDY","CACHE",
        "CADET","CAMEO","CARAT","CAULK","CHAFE","CHASM","CHIDE","CHORE","CINCH","CLEFT","CLUCK","CLUMP","CLUNG",
        "COBIA","COLIC","COLON","CONDO","CONGA","COPSE","COUCH","COVET","COZY","CRANE","CRAZE","CRIMP","CROAK",
        "CRONE","CROON","CURLY","DADDY","DAFFY","DAUNT","DECAL","DECAY","DECOY","DECRY","DELVE","DEVIL","DIGIT",
        "DINGO","DIVOT","DOGGY","DOLLY","DOWDY","DROWN","DUCHY","DUMPY","DUNCE","DUSTY","DWARF","DWELL","EASEL",
        "EERIE","EGRET","ELBOW","ELOPE","EMBED","ERASE","ERODE","ESSAY","ETHIC","EVADE","EXERT","EXILE","EXPEL",
        "EXULT","FANNY","FEIGN","FELON","FEMUR","FETCH","FIERY","FISHY","FLAKY","FLEET","FLINT","FLOUT","FLUME",
        "FLUNK","FLUTE","FOAMY","FOYER","FRISK","FRIZZ","FRUMP","FUGUE","GAUDY","GAUZE","GAVEL","GAWKY","GECKO",
        "GEESE","GENUS","GERMS","GIDDY","GIZMO","GLAZE","GLINT","GLOAT","GLOOM","GLYPH","GNASH","GNOME","GOLLY",
        "GOUGE","GRIPE","GROOM","GRUEL","GRUMP","GULCH","GUMBO","GYPSY","HAIKU","HAMMY","HARDY","HATCH","HAZEL",
        "HEAVE","HELIX","HIPPO","HIPPY","HITCH","HOIST","HORNY","HOUND","HOVER","HOWDY","HYENA","ICILY","IDYLL",
        "IMPEL","INANE","INCUR","INDIE","INERT","INFER","INGOT","IRATE","IRONY","ITCHY","JOUST","JUMPY","KHAKI",
        "KIOSK","KITTY","KNACK","KNAVE","KNEEL","KNELT","LAGER","LAITY","LARGO","LATCH","LEGGY","LIBEL","LILAC",
        "LIMBO","LITHE","LIVID","LLAMA","LOBBY","LOFTY","LOOPY","LORRY","LOWLY","LUMPY","MACHO","MAMBO","MATEY",
        "MAXIM","MEALY","MEATY","MEDIC","MELEE","MELON","MESSY","MIDGE","MINCE","MINTY","MOCHA","MOGUL","MOLDY",
        "MOOSE","MOUSY","MUCKY","MUGGY","NIFTY","NINNY","NIPPY","NUTTY","OAKEN","ODDLY","OFFAL","OFTEN","OGLED",
        "ONION","ORBIT","OVOID","PANEL","PANSY","PASTY","PATSY","PEACH","PEAKY","PEEVE","PICKY","PINEY","PINKY",
        "PLAID","PODGY","POOCH","POTTY","POUTY","PRIVY","PRUNE","PUDGY","PUFFY","PURGE","PYGMY","QUACK","QUALM",
        "QUELL","RABBI","RABID","RANGY","RASPY","RAVEN","RECTO","REEDY","REGAL","RENEW","REPEL","RERUN","RHYME",
        "RIPEN","RISEN","ROCKY","RUDDY","RUGBY","RUNNY","SAGGY","SANDY","SASSY","SAVVY","SCALD","SCALY","SEDAN",
        "SEEDY","SERVE","SHADY","SHAKY","SLANG","SLIMY","SOAPY","SOGGY","SONIC","SOOTY","SOPPY","SOUPY","SPANK",
        "SPARE","SPLAY","SPOOK","SPORE","SPRIG","SPUNK","SPURN","SQUAT","SQUID","STAID","STOIC","STONY","STRAP",
        "STRAW","STRIP","STRUT","SULKY","SULLY","SURLY","SWAMP","TABBY","TAFFY","TANGY","TAPIR","TARDY","TAWNY",
        "TEPID","TERSE","TESTY","TIDAL","TOADY","TODDY","TOPIC","TORTE","TRILL","TRIPE","TRITE","TROUT","TUBER",
        "TUBBY","TULLE","TURBO","TWANG","TWEED","TWILL","TYING","ULCER","ULTRA","UMBRA","UNDUE","UNFIT","UNIFY",
        "UNLIT","UNMET","UNPIN","UNTIE","UNWED","URBAN","USHER","UVULA","VEINY","VISOR","VIXEN","VODKA","VOMIT",
        "VULVA","WACKY","WAKEN","WARTY","WAFER","WEEDY","WIMPY","WINCE","WITTY","WOODY","WORMY","WRUNG","YAPPY",
        "YUCKY","ZONAL","ZESTY",
        // plurals of 4-letter nouns (5-letter)
        "ACHES","ACRES","BALES","BALLS","BANDS","BANES","BANGS","BARKS","BARNS","BASES","BEADS","BEAMS","BEANS",
        "BEARS","BEATS","BELLS","BELTS","BENDS","BILLS","BINDS","BITES","BOARS","BOATS","BOLTS","BONDS","BOOKS",
        "BOOMS","BOOTS","CAGES","CALLS","CARDS","CARTS","CELLS","CHIPS","CLAMS","CLAPS","CLAYS","CLIPS","CLODS",
        "CLOGS","CLOTS","CLUBS","CLUES","COILS","COINS","COOKS","CORDS","CORKS","CORNS","COSTS","CRAMS","CRIBS",
        "CROPS","CROWS","CUBES","CURLS","DARES","DARTS","DAWNS","DEALS","DECKS","DEEDS","DESKS","DIETS","DOCKS",
        "DOORS","DRAGS","DRIPS","DROPS","DRUMS","DUSTS","EARLS","EDGES","FAILS","FALLS","FANGS","FARES","FARMS",
        "FATES","FEATS","FEEDS","FEELS","FERNS","FILLS","FILMS","FINDS","FIRES","FIRMS","FISTS","FLAGS","FLAPS",
        "FLAWS","FLEAS","FLIPS","FLOWS","FOAMS","FOLDS","FOLKS","FONTS","FOODS","FOOLS","FORDS","FORKS","FORMS",
        "FORTS","FROGS","FUNDS","GANGS","GEARS","GIFTS","GIRLS","GLOWS","GNATS","GOALS","GOWNS","GRABS","GRAMS",
        "GRINS","GRIPS","HAILS","HALLS","HANDS","HANGS","HARES","HARPS","HAWKS","HEADS","HEALS","HEAPS","HEARS",
        "HEELS","HERBS","HERDS","HILLS","HOLDS","HOOKS","HORNS","HOURS","HUNTS","IDEAS","JACKS","JAILS","JERKS",
        "JOLTS","KEEPS","KINDS","KINGS","KNOBS","KNOTS","LAKES","LAMBS","LAMPS","LANDS","LEADS","LEAPS","LENDS",
        "LIFTS","LINKS","LIONS","LISTS","LOADS","LOANS","LOCKS","LOOPS","LORDS","LUMPS","LUNGS","LUSTS","MAILS",
        "MEALS","MEATS","MEETS","MELTS","MENUS","MILLS","MINTS","MISTS","MOANS","MOLDS","MOTHS","NAILS","NECKS",
        "NEEDS","NOSES","PACKS","PAGES","PAINS","PALMS","PATHS","PEEKS","PEELS","PEERS","PICKS","PILLS","PLANS",
        "PLAYS","PLOTS","PLUGS","POEMS","POETS","POLLS","POOLS","PORTS","RACKS","RAILS","RAINS","RAMPS","RANKS",
        "RANTS","READS","REELS","RENTS","RINGS","RIOTS","RISES","RISKS","ROAMS","ROARS","ROLLS","ROOFS","ROOMS",
        "ROOTS","RUINS","SAILS","SANDS","SCARS","SEALS","SEAMS","SEEDS","SELLS","SENDS","SHINS","SHIPS","SHOES",
        "SIGNS","SILLS","SINKS","SKINS","SLAPS","SLIPS","SLOTS","SLUGS","SNOBS","SOCKS","SOILS","SOLES","SONGS",
        "SORES","SORTS","SOULS","SOUPS","SPINS","SPITS","SPOTS","SPURS","STABS","STAGS","STARS","STEMS","STEPS",
        "STEWS","STOPS","STUBS","STUDS","SULKS","SURFS","SWAPS","TACKS","TALKS","TEARS","TELLS","TENDS","TERMS",
        "TESTS","TICKS","TIDES","TILLS","TIRES","TOADS","TOLLS","TOMBS","TONGS","TOURS","TRAMS","TRAPS","TRIPS",
        "TROTS","TUFTS","TURFS","TUSKS","TWINS","URGES","VEILS","VEINS","VESTS","VIBES","VOIDS","WAGES","WALKS",
        "WALLS","WANTS","WARDS","WARNS","WARPS","WASPS","WEEDS","WEEKS","WHIPS","WINDS","WINGS","WIRES","WORMS",
        "WRENS","WRITS","YARDS","YARNS","YEARS","YELLS","YOLKS",
        // 5-letter words batch 2
        "SATED","HATED","NITRE","NITER","MITRE","TITER","EATER","PATER","LACER","FACER","PACER","DICER","NICER",
        "TRACED","PLACED","SPACED","GRACED","BRACED","RISEN","BIDET","RIVET","RIPEN","GIVEN","LIVEN","RIVEN",
        "WIZEN","DOZEN","TOKEN","WOKEN","SPOKE","BROKE","CHOKE","SMOKE","STOKE","PRICK","TRICK","BRICK","CLICK",
        "SLICK","THICK","FLICK","QUICK","STICK","CHICK","KNOCK","BLOCK","CLOCK","FLOCK","SHOCK","STOCK","SMOCK",
        "CRACK","BLACK","SLACK","SNACK","STACK","TRACK","CHALK","BLAND","BRAND","GRAND","GLAND","STAND","GREED",
        "BLEED","BREED","CREED","FREED","TREED","SPEED","TWEED","STEED","CREEK","CHEEK","SLEEK","SPEAK","CREAK",
        "FREAK","SNEAK","STEAK","TWEAK","WREAK","BLEAK","FIEND","SCENE","QUEEN","GENRE","SUEDE","THANE","BRAWL",
        "CRAWL","DRAWL","SCRAWL","SPELL","SHELL","SMELL","DRILL","FRILL","GRILL","QUILL","SHILL","SKILL","SPILL",
        "STILL","SWILL","TRILL","BLOOM","BROOM","GLOOM","GROOM","VROOM","CROUP","GROUP","DROOP","SNOOP","STOOP",
        "SWOOP","TROOP","WHOOP","SCOOP","RAPID","VALID","VIVID","TIMID","RIGID","HUMID","FETID","FLUID","DRUID",
        "SQUID","OUTER","INNER","UPPER","UNDER","INTER","EXTRA","INTRA","ULTRA","PETAL","METAL","FETAL","FATAL",
        "NATAL","TOTAL","LOCAL","FOCAL","VOCAL","MODAL","TIDAL","TONAL","VIRAL","FINAL","RIVAL","TRIAL","VITAL",
        "BASAL","NASAL","LEGAL","ALGAL","PENAL","RENAL","VENAL","PAPAL","ADIEU","BAYOU","BLAZE","CRAZE","DAZE",
        "GLAZE","GRAZE","HAZE","MAZE","PHASE","CRAZE","GAZE","RAGED","CAGED","PAGED","WAGED","STAGED","BARED",
        "FARED","PARED","RARED","CARED","GLARE","BLARE","FLARE","SNARE","STARE","SHARE","SPARE","SWEAR","SWORE",
        "ADORE","CHORE","SHORE","SPORE","STORE","SCORE","SNORE","SWORE","LAPSE","ELAPSE","LACED","RACED","PACED",
        "FACED","BASED","CASED","CHASED","ERASED","PHASED","BRAISE","PRAISE","RAISED","GLAZED","BLAZED","CRAZED",
        "FAZED","HAZED","MAZED","GAZED","RAZED","LAZED","DAZED","OZONE","STONE","PHONE","PRONE","DRONE","THRONE",
        "ALONE","CLONE","ATONE","SHONE","BLOWN","FLOWN","GROWN","KNOWN","SHOWN","SOWN","FROWN","DROWN","CROWN",
        "BROWN","CLOWN","DRAWN","SPAWN","YAWN","DAWN","BLOOM","FLOOM","GROOM","BROOM","VROOM","WHOOM","ZOOM",
        "PROOF","SPOOF","ALOOF","HOOF","ROOF","GOOF","COOL","FOOL","POOL","SPOOL","STOOL","DROOL","SCHOOL",
        "PRICK","TRICK","BRICK","FLICK","QUICK","STICK","CHICK","CLICK","SLICK","THICK","LEMON","DEMON","MELON",
        "FELON","NYLON","RAYON","BATON","BARON","CANON","MASON","SATIN","CABIN","RAVEN","HAVEN","GIVEN","LIVEN",
        "DRIVEN","RISEN","TOKEN","WOKEN","BROKEN","SPOKEN","STOLEN","CHOSEN","FROZEN","PROVEN","WOVEN","RAVEN",
        "OAKEN","TAKEN","RISEN","AWOKEN","GOLDEN","OLDEN","SULLEN","FALLEN","SWOLLEN","STOLEN","WOOLEN","STOLEN",
        "ASHEN","LINEN","RIVEN","LITHE","TITHE","BLITHE","SCYTHE","SWATHE","BATHE","LATHE","SMITE","QUITE","SUITE",
        "WHITE","WRITE","SPOKE","BLOKE","CLOAK","SOAK","CROAK","GROAN","PLAIN","TRAIN","BRAIN","CHAIN","DRAIN",
        "GRAIN","SLAIN","SPAIN","SPRAIN","STAIN","SWAIN","AGAIN","ATTAIN","CRANE","PLANE","BLAME","FLAME","FRAME",
        "SHAME","TAME","CLAIM","FLAIL","SNAIL","TRAIL","GRAIL","QUAIL","FRAIL","WAIL","MAIL","SAIL","PAIL","NAIL",
        "HAIL","FAIL","BAIL","RAIL","TAIL","JAIL","FLAIL","TRAIL","SNAIL","QUAIL","GRAIL","FRAIL","BRAIL",
        "ELBOW","BELOW","MELON","FELON","NYLON","TALON","HALON","SALON","AVON","COLON","BISON","MASON","SIREN",
        "RIVEN","LIVEN","RISEN","GIVEN","DRIVEN","TOKEN","BROKEN","STOLEN","FROZEN","PROVEN","CHOSEN","WOVEN",
        "BEGUN","RERUN","UNPIN","UNWED","UNTIE","UNFIT","UNDUE","UNTIL","UNSEW","UNDO","UNZIP","UNCUT","UNFED",
        "UNCLE","UNDER","UNLIT","UNMET","UNSET","UNTAR","UNIFY","UNBOX","ADDED","AHED","AILED","AIMED","AIRED",
        "BALED","CARED","DARED","DINED","ENDED","FILED","FINED","FIRED","GIVEN","HALED","HIRED","JOKED","LINED",
        "LIKED","LIVED","LOVED","LURED","MATED","MINED","MOVED","NAMED","NOTED","OWNED","PACED","PAVED","PILED",
        "PINED","PIPED","POSED","RACED","RAKED","RATED","RAVED","RILED","RIPED","SAVED","TONED","TUNED","TYPED",
        "URGED","VOTED","WADED","WAGED","WAVED","WIPED","WIRED","ZONED","FACED","FAKED","FARED","FAZED","FUMED",
        "FUSED","GAMED","GIBED","HAZED","HIKED","HOPED","HOSED","HYPED","KITED","LAKED","LAVED","LAZED","LIMED",
        "MIRED","MOPED","MUTED","POKED","RAZED","RIMED","ROBED","ROPED","ROVED","RULED","SAGED","SITED","SIZED",
        "TIRED","TOTED","BIKED","BORED","CAGED","CAKED","CANED","CAPED","CASED","CAVED","CITED","CODED","COKED",
        "CONED","COPED","CORED","DATED","DAZED","DIKED","DIMED","DOZED","DUPED",
        // 5-letter -ING words
        "ACING","AGING","AIDING","AIMING","AIRED","BAKING","BALING","BARING","BASING","BEING","BIDING","BIKING",
        "BITING","BOKING","CAGING","CAKING","CANING","CAPED","CARING","CASING","CAVING","CITING","CODING",
        "COKING","CONING","COPING","CORING","DARING","DATING","DAZING","DIKING","DINING","DOTING","DUPING",
        "EKING","FACING","FADING","FAKING","FARING","FAXING","FILING","FINING","FIRING","FUMING","FUSING",
        "GAMING","GAZING","GIVING","GLOAT","GROAN","HALING","HAZING","HIKING","HIRING","HOPING","HOSING",
        "JOKING","KITING","LACING","LAVING","LAZING","LIKING","LIMING","LINING","LURING","MATING","MAZING",
        "MINING","MIRING","MOPING","MOVING","MUTING","NAMING","NOTING","PACING","PAVING","PIKING","PILING",
        "PINING","PIPING","POKING","POSING","RACING","RAKING","RATING","RAVING","RAZING","RILING","RIMING",
        "ROBING","ROPING","ROVING","RULING","SAVING","SITING","SIZING","TAMING","TIMING","TIRING","TONING",
        "TOTING","TUNING","TYPING","VOTING","WADING","WAGING","WAVING","WIPING","WIRING","ZONING",
    ]

    // MARK: 6-letter words
    static let words6: Set<String> = [
        "ABSENT","ACCENT","ACCEPT","ACCESS","ANIMAL","ANNUAL","ANSWER","ANYONE","ATTACK","BATTLE","BEAUTY","BEHIND",
        "BELONG","BETTER","BEYOND","BITTER","BRIDGE","BROKEN","BUDGET","BUTTER","CANDLE","CARBON","CASTLE","CATTLE",
        "CAUGHT","CHANCE","CHANGE","CHARGE","CHEEKY","CHERRY","CHOICE","CHOOSE","CIRCLE","CLEVER","CLOSER","COFFEE",
        "COMBAT","COMMIT","CORNER","COTTON","COUPLE","CREATE","CUSTOM","DAMAGE","DANGER","DEBATE","DECIDE","DEFEAT",
        "DEFEND","DESIGN","DETAIL","DINNER","DIRECT","DIVIDE","DOUBLE","ENOUGH","ENTITY","ENTIRE","ESCAPE","EVENTS",
        "EXPERT","EXTEND","FACTOR","FALLEN","FAMILY","FAMOUS","FASTER","FATHER","FIGURE","FINGER","FOLLOW","FOREST",
        "FORMAL","FROZEN","FUTURE","GARDEN","GATHER","GENTLE","GLOBAL","GOVERN","GRAVEL","GROUND","GROWTH","HAPPEN",
        "HARBOR","HUNGRY","HUNTER","IMPACT","INCOME","INSULT","ISLAND","ITSELF","JACKET","JUNGLE","JUNIOR","KEEPER",
        "KERNEL","KNIGHT","LADDER","LANCER","LAUNCH","LEADER","LESSEN","LETTER","LISTEN","LITTLE","LOVING","LUXURY",
        "MAGNET","MANNER","MARBLE","MARKET","MATTER","MEMBER","MIGHTY","MIRROR","MODERN","MOMENT","MORTAL","MOTHER",
        "MOTION","MUSCLE","MUTUAL","MYSELF","NARROW","NATION","NATURE","NEARLY","NEEDLE","OBJECT","OLDEST","ONLINE",
        "ORANGE","ORIGIN","OUTPUT","PARENT","PATROL","PEOPLE","PLANET","PLAYER","PLENTY","POCKET","PONDER","PORTAL",
        "PRETTY","PRISON","PROPER","PUBLIC","PURPLE","PUZZLE","RABBIT","RADIAL","RANDOM","REASON","RECORD","REFUSE",
        "REMAIN","REMOTE","RENTAL","REPAIR","REPEAT","RESCUE","RESULT","RETURN","REVIEW","RISING","ROCKET","ROTATE",
        "RUSTIC","SAMPLE","SCHEME","SCHOOL","SEARCH","SECURE","SELECT","SERIES","SIGNAL","SILVER","SIMPLE","SINGLE",
        "SISTER","SLIGHT","SMOOTH","SNATCH","SOCIAL","SOCKET","SOLACE","SOLVER","SORROW","SORTED","SOURCE","SPREAD",
        "SQUARE","STABLE","STATUE","STEADY","STRIDE","STRIKE","STRING","STRONG","SUMMER","SUPPLY","SWITCH","SYSTEM",
        "TARGET","THEORY","THIRTY","THOUGH","THREAD","THREAT","THROAT","TIMBER","TONGUE","TRAVEL","TRIPLE","TUNNEL",
        "TURTLE","TWELVE","TWENTY","UPWARD","USEFUL","WISDOM","WITHIN","WONDER","WOODEN","WRITER","YELLOW",
        // additional 6-letter words
        "ABDUCT","ABUSED","ACROSS","ADHERE","ADVERB","AERIAL","AFFECT","AFFIRM","AFFORD","AGENDA","AGHAST","AGREED",
        "ALBEIT","ALBINO","ALCOVE","ALIGHT","ALLIED","ALLURE","ALMOST","ALPINE","AMUSED","ANALOG","ANEMIA","ANKLET",
        "ANNEAL","ANOINT","APLOMB","APPALL","ARCHED","ARDENT","ARGYLE","ARMOUR","ASPIRE","ASSENT","ASSORT","ASTRAY",
        "ATTAIN","ATTIRE","AUGUST","AVERSE","BABBLE","BADGER","BAMBOO","BARREL","BARREN","BECKON","BEDLAM","BEHOLD",
        "BELFRY","BEMOAN","BESTOW","BETRAY","BEWARE","BLAZER","BLIGHT","BONNET","BORDER","BOUNTY","BUFFET","BUMBLE",
        "BURROW","CACKLE","CAMPER","CANOPY","CARPET","CASKET","CAVERN","CENSUS","CHAPEL","CHASTE","CHERUB","CHROME",
        "CIPHER","CLOVEN","COERCE","COHORT","COMPLY","CONCUR","CONDOR","CONSUL","CONVEX","CONVEY","CORTEX","DARKEN",
        "DAZZLE","DECEIT","DECENT","DECREE","DEFILE","DEJECT","DETAIN","DIFFER","DISMAL","DISPEL","DIVERT","DOLLOP",
        "DONKEY","DOTING","DRAWER","DURESS","EERILY","EFFIGY","ELAPSE","ELATED","ELDEST","EMBODY","EMERGE","EMPLOY",
        "ENGAGE","ENGULF","ERRANT","EVENLY","EVOLVE","EXCISE","EXCITE","EXEMPT","EXHORT","EXPOSE","FAMINE","FATHOM",
        "FEEBLE","FELINE","FERRET","FETISH","FICKLE","FIDDLE","FIERCE","FISCAL","FITFUL","FIZZLE","FLAWED","FLEDGE",
        "FLINCH","FLOPPY","FLORAL","FLORID","FLUENT","FORBID","FOREGO","FORGED","FRENZY","FRUGAL","GAMBLE","GARBLE",
        "GARLIC","GARNET","GARNER","GIBBET","GIGGLE","GILDED","GOBLIN","GOSSIP","GREEDY","GROVEL","GRUDGE","HAGGLE",
        "HAMLET","HANDLE","HANKER","HAMPER","HEARTY","HEAVEN","HERALD","HEREIN","HERMIT","HIKING","HOOPLA","HORRID",
        "HUDDLE","HUMBLE","HUSTLE","IGNITE","IMPEDE","IMPURE","INDICT","INFECT","INFUSE","INNATE","INSANE","INSERT",
        "INWARD","JACKAL","JESTER","JOSTLE","JOVIAL","JUGGLE","JUMBLE","LAVISH","LEADEN","LETHAL","LOOSEN","MANGLE",
        "MANTLE","MEDDLE","MELODY","MENTAL","MIDDAY","MIDGET","MINGLE","MISHAP","MODEST","MOLTEN","MORTAR","MOSAIC",
        "MUTTER","MYRIAD","NAMELY","NATTER","NETTLE","NIMBLE","NOODLE","NOTION","NUZZLE","OBLONG","OBTUSE","OCCUPY",
        "OPPOSE","ORDEAL","ORNATE","OUTLAW","OUTWIT","PADDLE","PAMPER","PARDON","PASTRY","PATRON","PEBBLE","PEDDLE",
        "PENURY","PICNIC","PIRATE","PLACID","PLAGUE","PLAQUE","PLIANT","PODIUM","POUNCE","PREFER","PRIORY","PROTON",
        "PUDDLE","PUMMEL","PUPPET","QUIRKY","RACKET","RAMBLE","RANCID","RANKLE","RATTLE","RAGGED","RAVAGE","RECKON",
        "RECOIL","RENDER","REPENT","RESENT","REVEAL","RIDDLE","RIPPLE","ROBUST","ROTTEN","RUBBLE","RUFFLE","RUGGED",
        "SAVAGE","SCORCH","SCRAWL","SCRIBE","SCRUFF","SERAPH","SERENE","SETTLE","SHAGGY","SHIFTY","SHIVER","SHREWD",
        "SHRIEK","SHRINK","SICKEN","SIZZLE","SKEWER","SKIMPY","SLEAZY","SLEUTH","SLUDGE","SMUDGE","SNOOTY","SOLEMN",
        "SOOTHE","SORDID","SPLEEN","SPRAWL","SQUALL","SQUIRM","STUPID","SUBDUE","SUBMIT","SUBTLE","SULLEN","SUMMIT",
        "SUNDRY","SWERVE","TACKLE","TAMPER","TASSEL","TATTER","TENDER","TETHER","THATCH","TINGLE","TOPPLE","TOTTER",
        "TRIFLE","TRUDGE","TUMBLE","TUSSLE","TWITCH","WANDER","WANTON","WARBLE","WELTER","WICKED","WITHER","WOBBLE",
        "WRITHE","YEOMAN",
        // 6-letter -ERS forms
        "BAKERS","BIKERS","BITERS","CAPERS","CARERS","CATERS","CAVERS","CIDERS","DINERS","DIVERS","DOTERS","FAKERS",
        "FARERS","GAMERS","GAPERS","GAZERS","GIVERS","HATERS","HIDERS","HIKERS","HIRERS","JOKERS","LIFERS","LIKERS",
        "LIMERS","LITERS","LIVERS","LOSERS","LOVERS","MAKERS","MINERS","MISERS","MITERS","MOVERS","NOTERS","OATERS",
        "OGLERS","PAVERS","PIKERS","PIPERS","POKERS","RAKERS","RAVERS","RIDERS","RISERS","ROPERS","ROVERS","RULERS",
        "SAVERS","SIZERS","TAKERS","TAMERS","TAPERS","TIMERS","TOKERS","TONERS","TOTERS","TUNERS","VIPERS","VOTERS",
        "WADERS","WAGERS","WAVERS","WIPERS","YOKERS",
        // more 6-letter words
        "CASING","CLOVER","COPPER","DANCER","DANCED","DARKER","DIALED","DIVING","DOLLAR","DRIVEN","DRIVER","DUSTED",
        "EITHER","ERASED","FAIRER","FINDER","FINEST","FIXING","FONDER","FOOTED","FORKED","FUNDED","GIFTED","GLIDED",
        "GLIDER","GRADED","GRADER","GRAYER","GRIPER","HANDED","HARDER","HATRED","HEATED","HEATER","HELPER","HIGHER",
        "HINTED","HOTTER","HUNTED","LANDED","LASTED","LATHER","LEAPED","LEAPER","LEASED","LENDER","LINKED","LOFTED",
        "LOUDER","MAILED","MELTED","MENDED","MINDER","MISSED","MOLDED","MOORED","NESTED","NETTED","NICKED","NIPPED",
        "NOBLER","PASTED","PLANED","PLANER","PLATED","PLATER","PLAYED","POISED","POOLED","POSTED","POURED","PRICED",
        "PRICER","RAISED","RAISER","RANKED","REELED","RENTED","RIFLED","RISKED","ROLLED","ROOTED","RUINED","SAILED",
        "SEALED","STAKED","STATED","STAYED","STONED","STORED","STYLED","SULKED","SUITED","SURFED","SURGED","TAILED",
        "TALKED","TARRED","TASTED","TENTED","TESTED","TILTED","TINTED","TIPPED","TITLED","TOILED","TOLLED","TOPPED",
        "TOSSED","TOUTED","TRADED","UNITED","VARIED","VENTED","VIEWED","WAITED","WALLED","WANTED","WARDED","WARNED",
        "WARPED","WASHED","WASTED","WELDED","WETTED","WINDED","WINGED","WORDED","WORKED","YANKED","ZIPPED","ZESTED",
        // missing 6-letter words: -ATER,-ACER,-ITER,-ICER,-LITER
        "PLACER","SKATER","SLATER","CRATER","GRATER","STATER","TRACER","SPACER","SLICER","RACER",
        "PLACERS","SLATERS","CRATERS","GRATERS","TRACERS","SPACERS","SLICERS",
        "LITERS","MITERS","NITERS","TITERS","BITERS","CITERS","PLACID","PLACED","TRACED","SPACED","GRACED","BRACED",
        "PLACES","TRACES","SPACES","GRACES","BRACES","FACERS","PACERS","LACERS","RACERS","ICERS","DICERS","RICERS",
        // 6-letter words batch 3: common everyday words
        "ABLAZE","ABOARD","ACCRUE","ACTING","ACTUAL","ADMIRE","ADROIT","ADVISE","AFFORD","AFIELD","AFLOAT","AFRAID",
        "AGEING","AGREED","AIMING","AIRMEN","ALBEIT","ANGLED","ANTLER","ARCHED","ASYLUM","BANTER","BARLEY","BEAMED",
        "BEATEN","BEGGAR","BEHAVE","BENDED","BLOUSE","BONDED","BOOTED","BOUGHT","BREWED","CALMLY","CANINE","CANYON",
        "CARTON","CASTOR","CAUSED","CEMENT","CHILLY","CHOSEN","COBALT","COILED","COINED","COLONY","COMEDY","COMPEL",
        "COSTED","COUNTY","COWARD","CRAFTY","CRISPY","CURSED","DEBRIS","DECADE","DEVISE","DEVOUR","DIGEST","DRIVEN",
        "DRYING","DUNKED","EARNED","EFFACE","EMPIRE","ENAMOR","ENTRAP","ENVIED","EQUITY","ERUPTS","FADING","FAULTY",
        "FINELY","FISHED","FITTED","FLOWED","FOILED","FUNDED","GIRDED","GLASSY","GRAINY","GRASSY","HEROIC","HOMAGE",
        "HONEST","ICICLE","IMPAIR","INFIRM","INLAND","INTAKE","INVENT","JOYFUL","JOYOUS","KINDLE","LAWFUL","LAYOUT",
        "LIFTED","LODGED","LONELY","MAINLY","MARINE","MENTOR","MORALS","NIMBLE","OFFSET","OPENED","PARTED","PEELED",
        "PIPING","PITTED","PLEDGE","PLOWED","PLYING","POPLAR","POURED","PRIMAL","PROMPT","PROBED","PURELY","QUEUED",
        "RESTED","ROBBED","RUSHED","RUSTED","SAFELY","SAVING","SCARCE","SEEMED","SHAPED","SIGHED","SIFTED","SLICED",
        "SMELLS","SOAKED","SOLVED","SPARED","SUNLIT","SWAYED","TARTAN","TIPPED","TOILED","TOSSED","TURNED","VALUED",
        "VETTED","WEDDED","ABLOOM","ABROAD","ABSORB","ACCENT","ACCORD","ACCUSE","ACQUIT","ADRIFT","ADVENT","ADVICE",
        "AERIAL","AFFECT","AFFINE","AFFIRM","AFFORD","AFOOT","AGENDA","AGHAST","AGREED","ALBEIT","ALBINO","ALCOVE",
        "ALIGHT","ALLIED","ALLURE","ALMOST","ALPINE","AMUSED","ANALOG","ANEMIA","ANKLET","ANNEAL","ANOINT","APLOMB",
        "APPALL","ARDENT","ARGYLE","ARMOUR","ASPIRE","ASSENT","ASSORT","ASTRAY","ATTAIN","ATTIRE","AUGUST","AVERSE",
        "BABBLE","BADGER","BAMBOO","BARREL","BARREN","BECKON","BEDLAM","BEHOLD","BELFRY","BEMOAN","BESTOW","BETRAY",
        "BEWARE","BLAZER","BLIGHT","BONNET","BORDER","BOUNTY","BUFFET","BUMBLE","BURROW","CACKLE","CAMPER","CANOPY",
        "CARPET","CASKET","CAVERN","CENSUS","CHAPEL","CHASTE","CHERUB","CHROME","CIPHER","CLOVEN","COERCE","COHORT",
        "COMPLY","CONCUR","CONDOR","CONSUL","CONVEX","CONVEY","CORTEX","DARKEN","DAZZLE","DECEIT","DECENT","DECREE",
        "DEFILE","DEJECT","DETAIN","DIFFER","DISMAL","DISPEL","DIVERT","DOLLOP","DONKEY","DOTING","DRAWER","DURESS",
        "EERILY","EFFIGY","ELAPSE","ELATED","ELDEST","EMBODY","EMERGE","EMPLOY","ENGAGE","ENGULF","ERRANT","EVENLY",
        "EVOLVE","EXCISE","EXCITE","EXEMPT","EXHORT","EXPOSE","FAMINE","FATHOM","FEEBLE","FELINE","FERRET","FETISH",
        "FICKLE","FIDDLE","FIERCE","FISCAL","FITFUL","FIZZLE","FLAWED","FLEDGE","FLINCH","FLOPPY","FLORAL","FLORID",
        "FLUENT","FORBID","FOREGO","FORGED","FRENZY","FRUGAL","GAMBLE","GARBLE","GARLIC","GARNET","GARNER","GIBBET",
        "GIGGLE","GILDED","GOBLIN","GOSSIP","GREEDY","GROVEL","GRUDGE","HAGGLE","HAMLET","HANDLE","HANKER","HAMPER",
        "HEARTY","HEAVEN","HERALD","HEREIN","HERMIT","HIKING","HOOPLA","HORRID","HUDDLE","HUMBLE","HUSTLE","IGNITE",
        "IMPEDE","IMPURE","INDICT","INFECT","INFUSE","INNATE","INSANE","INSERT","INWARD","JACKAL","JESTER","JOSTLE",
        "JOVIAL","JUGGLE","JUMBLE","LAVISH","LEADEN","LETHAL","LOOSEN","MANGLE","MANTLE","MEDDLE","MELODY","MENTAL",
        "MIDDAY","MIDGET","MINGLE","MISHAP","MODEST","MOLTEN","MORTAR","MOSAIC","MUTTER","MYRIAD","NAMELY","NATTER",
        "NETTLE","NIMBLE","NOODLE","NOTION","NUZZLE","OBLONG","OBTUSE","OCCUPY","OPPOSE","ORDEAL","ORNATE","OUTLAW",
        "OUTWIT","PADDLE","PAMPER","PARDON","PASTRY","PATRON","PEBBLE","PEDDLE","PENURY","PICNIC","PIRATE","PLACID",
        "PLAGUE","PLAQUE","PLIANT","PODIUM","POUNCE","PREFER","PRIORY","PROTON","PUDDLE","PUMMEL","PUPPET","QUIRKY",
        "RACKET","RAMBLE","RANCID","RANKLE","RATTLE","RAGGED","RAVAGE","RECKON","RECOIL","RENDER","REPENT","RESENT",
        "REVEAL","RIDDLE","RIPPLE","ROBUST","ROTTEN","RUBBLE","RUFFLE","RUGGED","SAVAGE","SCORCH","SCRAWL","SCRIBE",
        "SCRUFF","SERAPH","SERENE","SETTLE","SHAGGY","SHIFTY","SHIVER","SHREWD","SHRIEK","SHRINK","SICKEN","SIZZLE",
        "SKEWER","SKIMPY","SLEAZY","SLEUTH","SLUDGE","SMUDGE","SNOOTY","SOLEMN","SOOTHE","SORDID","SPLEEN","SPRAWL",
        "SQUALL","SQUIRM","STUPID","SUBDUE","SUBMIT","SUBTLE","SULLEN","SUMMIT","SUNDRY","SWERVE","TACKLE","TAMPER",
        "TASSEL","TATTER","TENDER","TETHER","THATCH","TINGLE","TOPPLE","TOTTER","TRIFLE","TRUDGE","TUMBLE","TUSSLE",
        "TWITCH","WANDER","WANTON","WARBLE","WELTER","WICKED","WITHER","WOBBLE","WRITHE","YEOMAN","YELLOW","YONDER",
        "ZIPPER","ZOMBIE","ZONING","ZODIAC","ZENITH","ZEPHYR","ZEALOT","YARROW","YEARLY","WORKED","WORLDLY","WORTHY",
        "WOUNDS","WOWING","WRAITH","WRISTS","WRITER","YACHTS","YAMMER","YANKEE","YELLED","YELPED","YONDER","ZIGZAG",
        // 6-letter -ING words
        "BAKING","BIKING","BITING","CAGING","CAKING","CANING","CARING","CAVING","CITING","CODING","COKING","CONING",
        "COPING","CORING","DARING","DATING","DAZING","DIKING","DINING","DOTING","DUPING","FACING","FADING","FAKING",
        "FARING","FILING","FINING","FIRING","FUMING","FUSING","GAMING","GAZING","GIVING","HALING","HAZING","HIKING",
        "HIRING","HOPING","HOSING","JOKING","KITING","LACING","LAVING","LAZING","LIKING","LIMING","LINING","LURING",
        "MATING","MAZING","MINING","MIRING","MOPING","MOVING","MUTING","NAMING","NOTING","PACING","PAVING","PIKING",
        "PILING","PINING","PIPING","POKING","POSING","RACING","RAKING","RATING","RAVING","RAZING","RILING","RIMING",
        "ROBING","ROPING","ROVING","RULING","SAVING","SITING","SIZING","TAMING","TIMING","TIRING","TONING","TOTING",
        "TUNING","TYPING","VOTING","WADING","WAGING","WAVING","WIPING","WIRING","ZONING","ADDING","AIMING","ASKING",
        "BOWING","BOXING","BUYING","COPING","CRYING","DARING","GIVING","HAVING","HIDING","HIRING","LIVING","LOVING",
        "MAKING","MOPING","PAYING","POKING","RISING","RULING","SAYING","SEWING","TAKING","TYING","USING","VOTING",
        "BARING","BASING","BIKING","BORING","BOWING","BOXING","CAKING","CANING","CODING","COKING","CONING","COVING",
        "CUBING","CURING","DICING","DIKING","DIMING","DINING","DIVING","DOING","DOPING","DOSING","DOTING","DOZING",
        "DUNING","DUPING","EKING","FAKING","FARING","FAZING","FILING","FINING","FIRING","FUMING","FUSING","GAPING",
        "GAZING","GIBING","GIVING","GLOVING","GLUING","HOKING","HOLING","HONING","HOPING","HOSING","JAPING","JIBING",
        "JOKING","LAKING","LAMING","LANING","LAVING","LAZING","LIMING","LINING","LIVING","LOPING","LOSING","LOVING",
        "LUBING","LURING","LUSTING","MAKING","MATING","MAZING","MIMING","MINING","MIRING","MOPING","MOVING","MUTING",
        "NAMING","NOTING","OGLING","PACING","PALING","PAVING","PILING","PINING","PIPING","POKING","POLING","POSING",
        "RACING","RAKING","RAPING","RATING","RAVING","RAZING","RIDING","RILING","RIMING","RISING","ROBING","ROPING",
        "ROVING","RULING","SAVING","SIRING","SITING","SIZING","TAMING","TAPING","TILING","TIMING","TIRING","TONING",
        "TOTING","TUBING","TUNING","TYPING","VOTING","WADING","WAGING","WAKING","WANING","WAVING","WIPING","WIRING",
        "YOKING","ZONING",
    ]

    // MARK: 7-letter words
    static let words7: Set<String> = [
        "ABANDON","ABILITY","ABSOLVE","ABSTAIN","ACCLAIM","ACCOUNT","ACCUSED","ACHIEVE","ACQUIRE","ADAMANT",
        "ADAPTED","ADDRESS","ADJOURN","ADVANCE","ADVERSE","AGITATE","AGONIZE","AILMENT","ALLEGED","ALREADY",
        "ALTERED","AMATEUR","AMBIENT","ANCIENT","ANDROID","ANIMATE","ANXIOUS","APPROVE","ARDUOUS","ASPHALT",
        "ASSUMED","ATTEMPT","ATTRACT","AUCTION","AUDIBLE","AWKWARD","BALCONY","BALLAST","BELOVED","BENEATH",
        "BERSERK","BETWEEN","BLOSSOM","BOMBARD","BREATHE","BRIGADE","BROUGHT","BURNISH","CABINET","CAPABLE",
        "CAPTAIN","CAPTURE","CAREFUL","CATALOG","CEILING","CENTURY","CHAOTIC","CHIEFLY","CLARITY","CLASSIC",
        "CLEANSE","CLIMATE","CLUSTER","COLLECT","COMFORT","COMMEND","COMPLEX","CONCEAL","CONDEMN","CONFIRM",
        "CONFUSE","CONNECT","CONSENT","CONSIST","CONTAIN","CONTEXT","CONTROL","CONQUER","COURAGE","COVERED",
        "CRUCIAL","CRUMBLE","CULTURE","CURIOUS","CURRENT","CUSHION","DECRYPT","DELIGHT","DELIVER","DEVELOP",
        "DEVOTED","DIGITAL","DIPLOMA","DISABLE","DISMISS","DISTURB","DIVERSE","DIVIDED","DORMANT","DYNASTY",
        "ECLIPSE","EDUCATE","ELECTED","ELEVATE","EMBRACE","ENCHANT","ENFORCE","ENHANCE","ENLARGE","ENRICH",
        "ENROLL","ENTITLE","EPISODE","EXTREME","EVIDENT","EXAMINE","EXECUTE","EXHAUST","EXPLAIN","EXPLODE",
        "EXPLORE","EXPRESS","EXTRACT","FAILURE","FANTASY","FASHION","FERTILE","FINALLY","FINDING","FLUTTER",
        "FOCUSED","FOREIGN","FORTUNE","FOUNDED","GENUINE","GRAMMAR","GRANTED","GRAVITY","GREATER","HARMONY",
        "HARVEST","HEALTHY","HOLIDAY","HONORED","HOSTILE","HOWEVER","HUNDRED","IMAGINE","IMMENSE","IMPULSE",
        "INCLUDE","INSPIRE","INSTEAD","INTENSE","ISOLATE","JOURNEY","JUSTICE","KNOWING","KINGDOM","LABELED",
        "LANDING","LEARNED","LEISURE","LIBERAL","LIMITED","LITERAL","LOGICAL","LOYALTY","MENTION","MIGRATE",
        "MILLION","MIRACLE","MISSING","MIXTURE","MONITOR","MONTHLY","MYSTERY","NETWORK","NEUTRAL","NOTABLE",
        "NOTHING","NOURISH","OBSCURE","OBVIOUS","OFFENSE","OPERATE","OPINION","OPTIMAL","ORGANIC","OUTLINE",
        "OUTSIDE","PAINFUL","PATIENT","PERFECT","PERFORM","PERSIST","PHANTOM","PLASTIC","POPULAR","PORTION",
        "POSTURE","PRESENT","PREVENT","PRIVATE","PROCESS","PRODUCE","PROGRAM","PROJECT","PROMOTE","PROTECT",
        "PROTEST","PROVIDE","PURPOSE","QUALIFY","QUALITY","REALITY","RECEIVE","RECOVER","REFLECT","REGULAR",
        "RELEASE","REPLACE","REQUIRE","RESOLVE","RESPECT","RESPOND","RESULTS","RESTORE","RETREAT","REVENUE",
        "REVERSE","REVIVAL","ROYALTY","SATISFY","SCATTER","SCIENCE","SECTION","SILENCE","SIMILAR","SKILLED",
        "SOCIETY","SOLDIER","SOMEHOW","SOMEONE","SPECIAL","STADIUM","STARTLE","STATION","STRETCH","STUDENT",
        "SUBJECT","SUGGEST","SUPPORT","SUPPOSE","SURVIVE","TACTICS","TEACHER","TENSION","THOUGHT","THROUGH",
        "TONIGHT","TOURISM","TRAGEDY","TRIUMPH","TRUSTED","UNCOVER","UNIFORM","UNKNOWN","UNRAVEL","URGENCY",
        "VACCINE","VENTURE","VERSION","VETERAN","VIBRANT","VILLAGE","VISIBLE","VOLCANO","WARRIOR","WEDDING",
        "WELCOME","WHETHER","WHISPER","WITNESS","WORKOUT","YOUNGER","ABSENCE","ACCRUED","ACRONYM","ALERTED",
        "ALIGNED","ALLOWED","AMAZING","ANALYZE","ANOTHER","ANTIQUE","APPLIED","ARRIVAL","ARTICLE","ASSURED",
        "AVERAGE","AWARDED","BALANCE","BANKING","BEARING","BECAUSE","BINDING","BONDING","BOOKING","BROUGHT",
        "CALLING","CAUSING","CHANGED","CHAPTER","CHARGED","CHARITY","CIRCUIT","CLAIMED","CLEANED","CLEARED",
        "COASTAL","COMBINE","COMMAND","COMPANY","COMPASS","COMPILE","CONCERN","CONDUCT","CONTENT","CONVERT",
        "COUNSEL","CREATED","CREATOR","DECIDED","DEFENSE","DEFINED","DENSITY","DESERVE","DIAGRAM","DIAMOND",
        "DISPLAY","DISTANT","DOUBLED","DRAWING","DRIVING","EARNING","ENABLED","ENTERED","EQUALLY","ESCAPED",
        "EXAMPLE","EXPOSED","FALLING","FITTING","FLOWING","FORCING","FORWARD","GAINING","GENERAL","GETTING",
        "GLOWING","GRADUAL","GUIDING","HANDLED","HELPING","HERSELF","HIGHEST","HIMSELF","HOLDING","HOUSING",
        "HUNTING","HURTING","IMPROVE","INITIAL","INVOLVE","JOINING","KEEPING","KILLING","LASTING","LEADING",
        "LENDING","LIFTING","LINKING","LISTING","LOADING","LOOKING","MANAGED","MAPPING","MAXIMUM","MEETING",
        "MELTING","MINIMUM","MOLDING","MORNING","MOUNTED","MUSICAL","NATURAL","NEITHER","NOTICED","NURSING",
        "OFFERED","OUTSIDE","PAINTED","PASSING","PATTERN","PENDING","PICKING","PLACING","PLAYING","POOLING",
        "POSTING","POURING","PRICING","PRIMARY","PRINTED","PROBLEM","PROFITS","PULLING","PUSHING","PUTTING",
        "RAISING","RANKING","READING","REPLACE","RESTING","RETURNS","REVISED","RUNNING","SEALING","SEEKING",
        "SELLING","SENDING","SERVING","SETTING","SHARING","SHOWING","SITTING","SLIDING","SLOWING","SOLVING",
        "SORTING","STAYING","STORING","SURGERY","TELLING","TESTING","TRADING","TURNING","WORKING",
        // 7-letter words batch 2: common everyday
        "ABIDING","ABOUNDS","ABSENCE","ABSORBS","ACCENTS","ACCORDS","ACCUSED","ADAPTED","ADHERED","ADMIRED",
        "ADOPTED","ADORNED","ADVISED","ALLOWED","ALTERED","AMASSED","AMENDED","AMOUNTS","AMUSING","ANGERED",
        "APPLIED","ARCHING","ARISING","ARRIVED","ASSUMED","ASSURED","AVOIDED","AWARDED","BAFFLED","BLOCKED",
        "CARRIED","COMPARE","DECIDED","DEVOTED","DIVIDED","DOUBLED","EXISTED","IGNORED","INVITED","LOCATED",
        "NOTICED","REMOVED","REPLIED","STARTED","STOPPED","STUDIED","UTTERED","WRAPPED","ABASHED","ABORTED",
        "ABRIDGE","ABSENCE","ACCEDED","ACCUSED","ACCRUED","ACROBAT","ACRONYM","AGROUND","AIRMAIL","ALCOHOL",
        "ALGEBRA","ALLEGED","ALMONDS","ALTERED","ALRIGHT","AMBIENT","ANNULAR","ANTONYM","ANYBODY","ANYWAYS",
        "ARCHWAY","ARDUOUS","ARMBAND","ARMHOLE","ARRANGE","ARTWORK","ASCRIBE","ATHLETE","AUDITOR","AWESOME",
        "BACKLOG","BALLGAME","BARGAIN","BAPTIZE","BEDTIME","BEEHIVE","BEESWAX","BENEFIT","BERSERK","BETWEEN",
        "BICYCLE","BIOLOGY","BIZARRE","BLANKET","BUDDING","BURNING","CALLING","CAPITAL","CAPTAIN","CAPTURE",
        "CAREFUL","CATALOG","CEILING","CENTURY","CHAMBER","CHANNEL","CHAPTER","CHARITY","CHICKEN","COMBINE",
        "COMMAND","CONTENT","CONTEST","CULTURE","CURIOUS","CURRENT","CURTAIN","CUTTING","DAYBREAK","DEBACLE",
        "DECIMAL","DEFENSE","DELIVER","DESTINY","DICTATE","DIGITAL","DIGNITY","DISCUSS","DISMISS","DISPOSE",
        "DISTURB","DIVERSE","DUNGEON","ECONOMY","EDITION","ELECTED","ELEMENT","ENCHANT","ENFORCE","EXAMINE",
        "EXHAUST","EXPLAIN","EXPLORE","EXPRESS","EXTRACT","FACTORY","FAILURE","FANTASY","FASHION","FERTILE",
        "FICTION","FINALLY","FINDING","FLUTTER","FOCUSED","FOREIGN","FORTUNE","FOUNDED","GENUINE","GODLIKE",
        "GRANTED","GRAVITY","GREATLY","HARMONY","HARVEST","HEALING","HEALTHY","HEARING","HELPING","HERDING",
        "HIGHWAY","HISTORY","HOLIDAY","HONORED","HOUSING","HUNDRED","HUNTING","HUSBAND","ILLEGAL","IMAGINE",
        "IMMENSE","IMPULSE","INCLUDE","INSPIRE","INSTEAD","INTENSE","ISOLATE","JOURNEY","JUSTICE","KNOWING",
        "KINGDOM","LANDING","LEARNED","LEISURE","LIBRARY","LIMITED","LITERAL","LOGICAL","LOYALTY","MENTION",
        "MIGRATE","MILLION","MIRACLE","MISSING","MIXTURE","MONITOR","MONTHLY","MYSTERY","NETWORK","NEUTRAL",
        "NOTABLE","NOTHING","NOURISH","OBSCURE","OBVIOUS","OFFENSE","OPERATE","OPINION","OPTIMAL","ORGANIC",
        "OUTLINE","OUTSIDE","PAINFUL","PATIENT","PERFECT","PERFORM","PERSIST","PHANTOM","PLASTIC","POPULAR",
        "PORTION","POSTURE","PRESENT","PREVENT","PRIVATE","PROCESS","PRODUCE","PROGRAM","PROJECT","PROMOTE",
        "PROTECT","PROTEST","PROVIDE","PURPOSE","QUALIFY","QUALITY","REALITY","RECEIVE","RECOVER","REFLECT",
        "REGULAR","RELEASE","REPLACE","REQUIRE","RESOLVE","RESPECT","RESPOND","RESULTS","RESTORE","RETREAT",
        "REVENUE","REVERSE","REVIVAL","ROYALTY","SATISFY","SCATTER","SCIENCE","SECTION","SILENCE","SIMILAR",
        "SKILLED","SOCIETY","SOLDIER","SOMEHOW","SOMEONE","SPECIAL","STADIUM","STARTLE","STATION","STRETCH",
        "STUDENT","SUBJECT","SUGGEST","SUPPORT","SUPPOSE","SURVIVE","TACTICS","TEACHER","TENSION","THOUGHT",
        "THROUGH","TONIGHT","TOURISM","TRAGEDY","TRIUMPH","TRUSTED","UNCOVER","UNIFORM","UNKNOWN","UNRAVEL",
        "URGENCY","VACCINE","VENTURE","VERSION","VETERAN","VIBRANT","VILLAGE","VISIBLE","VOLCANO","WARRIOR",
        "WEDDING","WELCOME","WHETHER","WHISPER","WITNESS","WORKOUT","YOUNGER","ABIDING","ACHIEVE","ACHIEVE",
        "ACCOUNT","ACCUSED","ADAMANT","ACQUIRE","ADAPTED","ADDRESS","ADJOURN","ADVANCE","ADVERSE","AGITATE",
        "AGONIZE","AILMENT","ALLEGED","ALREADY","AMATEUR","AMBIENT","ANCIENT","ANDROID","ANIMATE","ANXIOUS",
        "APPROVE","ARDUOUS","ASPHALT","ASSUMED","ATTEMPT","ATTRACT","AUCTION","AUDIBLE","AWKWARD","BALCONY",
        "BALLAST","BELOVED","BENEATH","BERSERK","BLOSSOM","BOMBARD","BREATHE","BRIGADE","BROUGHT","BURNISH",
        "CABINET","CAPABLE","CAPTAIN","CAREFUL","CATALOG","CEILING","CENTURY","CHAOTIC","CLARITY","CLASSIC",
        "CLEANSE","CLIMATE","CLUSTER","COLLECT","COMFORT","COMMEND","COMPLEX","CONCEAL","CONDEMN","CONFIRM",
        "CONFUSE","CONNECT","CONSENT","CONSIST","CONTAIN","CONTEXT","CONTROL","CONQUER","COURAGE","COVERED",
        "CRUCIAL","CRUMBLE","CULTURE","CURIOUS","CURRENT","CUSHION","DECRYPT","DELIGHT","DELIVER","DEVELOP",
        "DEVOTED","DIGITAL","DIPLOMA","DISABLE","DISMISS","DISTURB","DIVERSE","DIVIDED","DORMANT","DYNASTY",
        "ECLIPSE","EDUCATE","ELECTED","ELEVATE","EMBRACE","ENCHANT","ENFORCE","ENHANCE","ENLARGE","EPISODE",
        "EXTREME","EVIDENT","EXAMINE","EXECUTE","EXHAUST","EXPLAIN","EXPLODE","EXPLORE","EXPRESS","EXTRACT",
        "FAILURE","FANTASY","FASHION","FERTILE","FINALLY","FINDING","FLUTTER","FOCUSED","FOREIGN","FORTUNE",
        "FOUNDED","GENUINE","GRAMMAR","GRANTED","GRAVITY","GREATER","HARMONY","HARVEST","HEALTHY","HOLIDAY",
        "HONORED","HOSTILE","HOWEVER","HUNDRED","IMAGINE","IMMENSE","IMPULSE","INCLUDE","INSPIRE","INSTEAD",
        "INTENSE","ISOLATE","JOURNEY","JUSTICE","KNOWING","KINGDOM","LABELED","LANDING","LEARNED","LEISURE",
        "LIBERAL","LIMITED","LITERAL","LOGICAL","LOYALTY","MENTION","MIGRATE","MILLION","MIRACLE","MISSING",
        "MIXTURE","MONITOR","MONTHLY","MYSTERY","NETWORK","NEUTRAL","NOTABLE","NOTHING","NOURISH","OBSCURE",
        "OBVIOUS","OFFENSE","OPERATE","OPINION","OPTIMAL","ORGANIC","OUTLINE","OUTSIDE","PAINFUL","PATIENT",
        "PERFECT","PERFORM","PERSIST","PHANTOM","PLASTIC","POPULAR","PORTION","POSTURE","PRESENT","PREVENT",
        "PRIVATE","PROCESS","PRODUCE","PROGRAM","PROJECT","PROMOTE","PROTECT","PROTEST","PROVIDE","PURPOSE",
        "QUALIFY","QUALITY","REALITY","RECEIVE","RECOVER","REFLECT","REGULAR","RELEASE","REPLACE","REQUIRE",
        "RESOLVE","RESPECT","RESPOND","RESTORE","RETREAT","REVENUE","REVERSE","REVIVAL","ROYALTY","SATISFY",
        "SCATTER","SCIENCE","SECTION","SILENCE","SIMILAR","SKILLED","SOCIETY","SOLDIER","SOMEHOW","SOMEONE",
        "SPECIAL","STADIUM","STARTLE","STATION","STRETCH","STUDENT","SUBJECT","SUGGEST","SUPPORT","SUPPOSE",
        "SURVIVE","TACTICS","TEACHER","TENSION","THOUGHT","THROUGH","TONIGHT","TOURISM","TRAGEDY","TRIUMPH",
        "TRUSTED","UNCOVER","UNIFORM","UNKNOWN","UNRAVEL","URGENCY","VACCINE","VENTURE","VERSION","VETERAN",
        "VIBRANT","VILLAGE","VISIBLE","VOLCANO","WARRIOR","WEDDING","WELCOME","WHETHER","WHISPER","WITNESS",
        "WORKOUT","YOUNGER","ABSENCE","ACCLAIM","ACCOUNT","ACRONYM","ALIGNED","ALLOWED","ALTERED","AMAZING",
        "ANALYZE","ANOTHER","ANTIQUE","APPLIED","ARRIVAL","ARTICLE","ASSURED","AVERAGE","AWARDED","BALANCE",
        "BANKING","BEARING","BECAUSE","BINDING","BONDING","BOOKING","CALLING","CAUSING","CHANGED","CHAPTER",
        "CHARGED","CHARITY","CIRCUIT","CLAIMED","CLEANED","CLEARED","COASTAL","COMBINE","COMMAND","COMPANY",
        "COMPASS","COMPILE","CONCERN","CONDUCT","CONTENT","CONVERT","COUNSEL","CREATED","CREATOR","DECIDED",
        "DEFENSE","DEFINED","DENSITY","DESERVE","DIAGRAM","DIAMOND","DISPLAY","DISTANT","DOUBLED","DRAWING",
        "DRIVING","EARNING","ENABLED","ENTERED","EQUALLY","ESCAPED","EXAMPLE","EXPOSED","FALLING","FITTING",
        "FLOWING","FORCING","FORWARD","GAINING","GENERAL","GETTING","GLOWING","GRADUAL","GUIDING","HANDLED",
        "HELPING","HERSELF","HIGHEST","HIMSELF","HOLDING","HOUSING","HUNTING","HURTING","IMPROVE","INITIAL",
        "INVOLVE","JOINING","KEEPING","KILLING","LASTING","LEADING","LENDING","LIFTING","LINKING","LISTING",
        "LOADING","LOOKING","MANAGED","MAPPING","MAXIMUM","MEETING","MELTING","MINIMUM","MOLDING","MORNING",
        "MOUNTED","MUSICAL","NATURAL","NEITHER","NOTICED","NURSING","OFFERED","PAINTED","PASSING","PATTERN",
        "PENDING","PICKING","PLACING","PLAYING","POOLING","POSTING","POURING","PRICING","PRIMARY","PRINTED",
        "PROBLEM","PROFITS","PULLING","PUSHING","PUTTING","RAISING","RANKING","READING","RESTING","RETURNS",
        "REVISED","RUNNING","SEALING","SEEKING","SELLING","SENDING","SERVING","SETTING","SHARING","SHOWING",
        "SITTING","SLIDING","SLOWING","SOLVING","SORTING","STAYING","STORING","SURGERY","TELLING","TESTING",
        "TRADING","TURNING","WORKING",
        // 7-letter -ING words
        "ABIDING","ABUSING","ACHING","ACTING","ADDING","AIDING","AIMING","ASKING","BAKING","BALING","BARING",
        "BASING","BIKING","BITING","BOXING","BUYING","CAGING","CAKING","CANING","CARING","CAVING","CITING",
        "CODING","COKING","CONING","COPING","CORING","DARING","DATING","DAZING","DIKING","DINING","DOTING",
        "DUPING","FACING","FADING","FAKING","FARING","FILING","FINING","FIRING","FUMING","FUSING","GAMING",
        "GAZING","GIVING","HALING","HAZING","HIKING","HIRING","HOPING","HOSING","JOKING","KITING","LACING",
        "LAVING","LAZING","LIKING","LIMING","LINING","LURING","MATING","MAZING","MINING","MIRING","MOPING",
        "MOVING","MUTING","NAMING","NOTING","PACING","PAVING","PIKING","PILING","PINING","PIPING","POKING",
        "POSING","RACING","RAKING","RATING","RAVING","RAZING","RILING","RIMING","ROBING","ROPING","ROVING",
        "RULING","SAVING","SITING","SIZING","TAMING","TIMING","TIRING","TONING","TOTING","TUNING","TYPING",
        "VOTING","WADING","WAGING","WAVING","WIPING","WIRING","ZONING","ABATING","ABIDING","ABUSING","ACTING",
        "ADDING","AIDING","AIMING","AKING","ASKING","BAKING","BALING","BARING","BASING","BIKING","BITING",
        "BOXING","BUYING","CAGING","CAKING","CANING","CARING","CAVING","CITING","CODING","COKING","CONING",
    ]

    // MARK: 8-letter words (bonus)
    static let words8: Set<String> = [
        "BLANKETS","BRANCHES","CAPTURES","CARRYING","CHAPTERS","CLEANING","CLIMBING","CLOTHING","COLONIES",
        "COLORFUL","COMBINED","COMPLETE","CONFUSED","CONTAINS","CONTRACT","CONTRAST","CREATING","CREATIVE",
        "CROSSING","CULTURAL","DARKNESS","DEADLINE","DECREASE","DEFEATED","DESIGNED","DISASTER","DISCOVER",
        "DISTANCE","DISTINCT","DOCTRINE","DOMESTIC","DOMINANT","DRAMATIC","EARNINGS","EDUCATED","ELEMENTS",
        "ELEVATED","ENTERING","EQUATION","ESTIMATE","EVALUATE","EVERYONE","EXCHANGE","EXPANDED","EXPECTED",
        "EXTENDED","EXTERNAL","FAILURES","FAMILIAR","FEATURED","FEELINGS","FIGHTING","FINISHED","FOLLOWED",
        "FRACTION","FRAGMENT","FREQUENT","FRONTIER","FUNCTION","GENERATE","GRATEFUL","GREATEST","GUARDIAN",
        "GUIDANCE","HERITAGE","HORRIBLE","HUMANITY","IDENTIFY","IMAGINED","IMPROVED","INCLUDED","INCREASE",
        "INDICATE","INNOCENT","INSPIRED","INTERVAL","INVOLVED","ISOLATED","LAUNCHED","LEARNING","LIFETIME",
        "LISTENED","LOCATION","MEASURED","MOVEMENT","NEGATIVE","OVERLOOK","PEACEFUL","PLATFORM","PLEASURE",
        "POSITION","POSSIBLE","POWERFUL","PRACTICE","PREPARED","PRESSURE","PREVIOUS","PROBABLE","PROBLEMS",
        "PROGRESS","PROMISED","PROMOTED","PROVIDED","QUESTION","REALIZED","RECORDED","REFERRED","REMAINED",
        "REPORTED","REQUIRED","RESEARCH","RESERVED","RESOLVED","RESPONSE","RESULTED","REVEALED","REVERSED",
        "SCHEDULE","SELECTED","SEQUENCE","SHORTAGE","STRUGGLE","SUPPLIED","SWIMMING","TOGETHER","TRAVELED",
        "TROUBLED","CAPTURED","TREASURE","ABSOLUTE","ABSTRACT","ACCEPTED","ACCIDENT","ACCURATE","ACHIEVED",
        "ACQUIRED","ACTIVELY","ADAPTING","ADDITION","ADEQUATE","ADJUSTED","ADMITTED","ADVANCED","AFFECTED",
        "AFFIRMED","AFFORDED","AGREEING","ALERTING","AMENDING","APPLYING","ARRANGED","ASSIGNED","ASSORTED",
        "ATTACHED","ATTENDED","BALANCED","BECOMING","BELIEVED","BLOCKING","BRINGING","BUILDING","CALENDAR",
        "CHANGING","CHOOSING","CIRCULAR","CITIZENS","CLEARING","COLONIAL","COMPARED","COMPILED","COMPOSED",
        "COMPUTED","CONSIDER","CONSUMED","DETAILED","DIRECTED","DIVIDING","DOUBLING","EMERGING","ENABLING",
        "ENSURING","ENTITLED","ESCAPING","EXAMINED","EXCLUDED","EXISTING","FACTORED","GATHERED","GRANTING",
        "HANDLING","IMPORTED","INFORMED","INTENDED","INVESTED","LIMITING","MANAGING","MODIFIED","MOUNTING",
        "NATIONAL","OBTAINED","OCCUPIED","OCCURRED","ORDERING","ORIENTED","ORIGINAL","OUTLINED","OVERCOME",
        "PLANNING","POLISHED","PRODUCED","RELEASED","REMINDED","REPLACED","RETAINED","RETURNED","SERVICES",
        "SETTINGS","SITUATED","SLEEPING","SPENDING","STAFFING","STANDING","STARTING","STOPPING","STUDYING",
        "SUITABLE","TEACHING","THINKING","TRAINING","TREATING","ULTIMATE","UNIVERSE","UTILIZED","VALUABLE",
        "VISITING","WATCHING","WELCOMED"
    ]
}
