import Foundation

// MARK: - Result types

enum WordleLetterResult: Equatable {
    case correct   // green  — right letter, right position
    case present   // yellow — right letter, wrong position
    case absent    // gray   — letter not in word
}

struct WordleGuess: Identifiable {
    let id = UUID()
    let word: String          // 5 uppercase chars
    let result: [WordleLetterResult]
    var isSolved: Bool { result.allSatisfy { $0 == .correct } }
}

// MARK: - Game

struct WordleGame {
    let targetWord: String    // 5 uppercase letters
    let seed: Int
    let round: Int

    init(seed: Int, round: Int) {
        self.seed = seed
        self.round = round
        var rng = SeededRNG(seed: seed &+ round &* 1_000_003)
        self.targetWord = rng.shuffled(WordleGame.wordBank)[0]
    }

    func evaluate(guess raw: String) -> [WordleLetterResult] {
        let guess  = Array(raw.uppercased())
        let target = Array(targetWord)
        var result     = Array(repeating: WordleLetterResult.absent, count: 5)
        var targetUsed = Array(repeating: false, count: 5)
        var guessUsed  = Array(repeating: false, count: 5)

        // Pass 1: correct positions
        for i in 0..<5 {
            if guess[i] == target[i] {
                result[i]     = .correct
                targetUsed[i] = true
                guessUsed[i]  = true
            }
        }
        // Pass 2: present (wrong position)
        for i in 0..<5 {
            guard !guessUsed[i] else { continue }
            for j in 0..<5 {
                if !targetUsed[j] && guess[i] == target[j] {
                    result[i]    = .present
                    targetUsed[j] = true
                    break
                }
            }
        }
        return result
    }

    static func isValidGuess(_ word: String) -> Bool {
        let w = word.uppercased()
        return w.count == 5 && (wordBank.contains(w) || WordDictionary.words.contains(w))
    }

    // MARK: - Word bank (~2500 common 5-letter answer words)

    static let wordBank: [String] = [
        // A
        "ABACK","ABASH","ABATE","ABBEY","ABBOT","ABIDE","ABODE","ABORT","ABUSE","ABYSS",
        "ACHED","ACHES","ACORN","ACRES","ACTED","ACUTE","ADAGE","ADAPT","ADMIT","ADOBE",
        "ADOPT","ADORE","ADULT","AFTER","AGAIN","AGAVE","AGED","AGENT","AGILE","AGING",
        "AGLOW","AGONY","AGREE","AHEAD","AIDED","AIMED","ALARM","ALBUM","ALERT","ALGAE",
        "ALIKE","ALIGN","ALIVE","ALLAY","ALOOF","ALONE","ALONG","ALOUD","ALTER","AMBER",
        "AMBLE","AMEND","ANGEL","ANGER","ANGLE","ANGRY","ANNEX","ANTIC","ANVIL","APART",
        "APPLE","APPLY","APRON","ARDOR","ARENA","ARGUE","ARISE","ARMOR","AROMA","ARRAY",
        "ASIDE","ASKEW","ASSET","ATOLL","ATONE","ATTIC","AUDIT","AVOID","AWAKE","AWARD",
        "AWARE","AWFUL","AXLES",
        // B
        "BRACE","BRAIN","BRAND","BRAVE","BREAK","BREED","BRICK","BRIDE","BRIEF","BRINE",
        "BRINK","BROKE","BROOD","BROTH","BROWN","BADGE","BARGE","BASIC","BASIN","BASIS",
        "BATCH","BEACH","BEARD","BEAST","BEGAN","BEGIN","BEING","BELOW","BENCH","BILLY",
        "BINGO","BIRCH","BIRTH","BISON","BLAND","BLANK","BLAST","BLAZE","BLEAK","BLEED",
        "BLEND","BLESS","BLIND","BLOCK","BLOOD","BLOOM","BLOWN","BLUNT","BOARD","BOAST",
        "BRAWL","BRAWN","BREAM","BRISK","BROIL","BULLY","BURNS","BUYER","BASIL","BASTE",
        "BIKED","BITER","BITERS","BLARE","BLIMP","BLISS","BLOAT","BOXER","BROOK","BREVE",
        "BAKER","BAKED","BALES","BALLS","BANDS","BARNS","BASES","BEADS","BEAMS","BEARS",
        "BEATS","BELLS","BELTS","BENDS","BILLS","BITES","BOATS","BOLTS","BONDS","BONES",
        "BOOKS","BOOMS","BOOTS","BORES","BURNS","BUYER","BYTES",
        // C
        "CABIN","CAMEL","CANDY","CARRY","CATCH","CAUSE","CEDAR","CHAIN","CHALK","CHAMP",
        "CHAOS","CHARM","CHEAT","CHEEK","CHEER","CHESS","CHEST","CHIEF","CHILD","CHILI",
        "CHIME","CHIMP","CHINA","CHORD","CHUNK","CIVIC","CIVIL","CLAIM","CLAMP","CLANK",
        "CLASH","CLASP","CLASS","CLEAT","CLERK","CLICK","CLIMB","CLING","CLOAK","CLOCK",
        "CLONE","CLOSE","CLOTH","CLOUD","CLOWN","COACH","COBRA","COCOA","COLOR","COMET",
        "CORAL","COUNT","COURT","COVER","CRACK","CRAFT","CRAMP","CRANE","CRASH","CRAWL",
        "CREAK","CREAM","CREEK","CREEP","CREST","CRIME","CRISP","CROSS","CROWD","CROWN",
        "CRUEL","CRUSH","CRUST","CRYPT","CURRY","CURSE","CURVE","CYCLE","CARED","CANER",
        "CANER","CANES","CAPES","CARDS","CARTS","CASES","CAVES","CELLS","CHIPS","CLAMS",
        "CLAPS","CLAYS","CLIPS","CLODS","CLOGS","CLOTS","CLUBS","CLUES","COILS","COINS",
        "COOKS","CORDS","CORES","CORKS","CORNS","COSTS","CRAMS","CRIBS","CROPS","CROWS",
        "CUBES","CURLS","CITER","CITED","CATES","CARED","CACER","CAGER",
        // D
        "DAILY","DAISY","DANCE","DEPOT","DEPTH","DERBY","DIRTY","DITCH","DIVER","DIZZY",
        "DODGE","DOING","DONOR","DOUBT","DOUGH","DRAIN","DRAPE","DREAD","DREAM","DRESS",
        "DRIED","DRIFT","DRILL","DRINK","DRIVE","DRONE","DROOL","DROVE","DRUNK","DYING",
        "DARES","DARTS","DAWNS","DEALS","DECKS","DEEDS","DESKS","DIETS","DOCKS","DOMES",
        "DOORS","DOSES","DOVES","DRAGS","DRIPS","DROPS","DRUMS","DUNES","DUSTS","DATED",
        "DATER","DATES","DICER","DICED","DACES",
        // E
        "EAGLE","EARLY","EARTH","EATEN","EIGHT","ELITE","EMPTY","ENEMY","ENJOY","ENTER",
        "ENTRY","EQUAL","EVENT","EVERY","EXACT","EXIST","EXTRA","EARLS","EDGES","EATER",
        "EASED","EASES","EMCEE","ERODE","ESSAY","EVADE","EXERT","EXILE",
        // F
        "FABLE","FACET","FAIRY","FAITH","FANCY","FATAL","FEAST","FEVER","FIBER","FIELD",
        "FIEND","FIFTH","FIFTY","FIGHT","FINAL","FIXED","FLAIR","FLAME","FLARE","FLASH",
        "FLASK","FLESH","FLICK","FLIES","FLING","FLOAT","FLOCK","FLOOD","FLOOR","FLUSH",
        "FOCAL","FOGGY","FORAY","FORCE","FORGE","FORTE","FORUM","FOUND","FRAME","FRANK",
        "FREED","FRESH","FRONT","FROST","FROZE","FULLY","FUNNY","FADES","FAILS","FALLS",
        "FANGS","FARES","FARMS","FATES","FEATS","FEEDS","FEELS","FERNS","FILES","FILLS",
        "FILMS","FINDS","FIRES","FIRMS","FISTS","FLAGS","FLAPS","FLAWS","FLEAS","FLIPS",
        "FLOWS","FOAMS","FOLDS","FOLKS","FONTS","FOODS","FOOLS","FORDS","FORKS","FORMS",
        "FORTS","FROGS","FUMES","FUNDS","FUSES","FACED","FACER","FACERS","FACES","FARED",
        "FAKER","FAKED","FAKES","FELON","FEMUR","FETCH","FIERY","FLAKY","FLEET","FLINT",
        "FLUME","FLUNK","FLUTE","FOAMY","FOYER","FRISK","FUGUE",
        // G
        "GAMES","GHOST","GIRTH","GIVEN","GLAND","GLARE","GLASS","GLEAM","GLOBE","GLORY",
        "GLOSS","GLOVE","GOING","GRACE","GRADE","GRAIN","GRAND","GRANT","GRAPE","GRASP",
        "GRASS","GRATE","GRAVE","GRAVY","GRAZE","GREED","GREET","GRIEF","GRIND","GROAN",
        "GROIN","GROPE","GROSS","GROUT","GROVE","GROWL","GRUFF","GUARD","GUILD","GUILE",
        "GUILT","GUSTO","GALES","GANGS","GEARS","GERMS","GIFTS","GIRLS","GLOWS","GNATS",
        "GOALS","GOWNS","GRABS","GRAMS","GRINS","GRIPS","GAUDY","GAUZE","GAVEL","GECKO",
        "GEESE","GENUS","GIDDY","GIRTH","GIZMO","GLAZE","GLINT","GLOAT","GLOOM","GLYPH",
        "GNASH","GNOME","GOLLY","GOUGE","GRIPE","GROOM","GRUEL","GRUMP","GULCH","GUMBO",
        "GYPSY","GRADED",
        // H
        "HABIT","HAPPY","HARSH","HAVEN","HEDGE","HEIST","HENCE","HOARD","HOLLY","HONEY",
        "HONOR","HORSE","HOTEL","HOUSE","HUMAN","HUMOR","HURRY","HUSKY","HAILS","HALLS",
        "HANDS","HANGS","HARES","HARPS","HAWKS","HEADS","HEALS","HEAPS","HEARS","HEELS",
        "HERBS","HERDS","HIDES","HILLS","HOLDS","HOLES","HOMES","HOOKS","HORNS","HOURS",
        "HUNTS","HAIKU","HARDY","HATCH","HAUTE","HAZEL","HEAVE","HIPPO","HITCH","HOIST",
        "HOMER","HOUND","HOVER","HYENA","HATED","HATER","HIKED","HIKER","HIRES","HIRED",
        "HONER","HONES",
        // I
        "IMAGE","IMPLY","INDEX","INNER","INPUT","INTER","INTRO","ISSUE","IVORY","ICIER",
        "ICILY","IDYLL","IMPEL","INANE","INCUR","INDIE","INERT","INFER","INGOT","IRATE",
        "IRONY","ITCHY",
        // J
        "JELLY","JEWEL","JUICE","JUICY","JUMBO","JOUST","JUMPY",
        // K
        "KARMA","KAYAK","KNIFE","KNOCK","KNEEL","KHAKI","KIOSK","KITTY","KNACK","KNAVE",
        "KNELT","KINDS","KINGS","KNOBS","KNOTS","KEEPS",
        // L
        "LABEL","LANCE","LANKY","LAPSE","LARGE","LASER","LATER","LAUGH","LAYER","LEARN",
        "LEASE","LEAST","LEAVE","LEGAL","LEMON","LIGHT","LIMIT","LINER","LIVER","LOCAL",
        "LODGE","LOGIC","LOOSE","LOVER","LOWER","LOYAL","LUNAR","LUSTY","LYRIC","LAKES",
        "LAMBS","LAMPS","LANDS","LANES","LEADS","LEAPS","LENDS","LIFTS","LIKES","LIMES",
        "LINES","LINKS","LIONS","LISTS","LOADS","LOANS","LOCKS","LOOPS","LORDS","LOVES",
        "LUMPS","LUNGS","LUSTS","LACED","LACER","LACES","LAKER","LATED","LITER","LITRE",
        "LITERS","LATER","LAZED","LAZES","LIMBO","LITHE","LIVID","LOFTY","LOWLY",
        // M
        "MAGIC","MAJOR","MANOR","MAPLE","MARCH","MARSH","MATCH","MAYOR","MEDIA","MERCY",
        "MERIT","METAL","MIGHT","MINOR","MIRTH","MONEY","MONTH","MORAL","MOUTH","MOVIE",
        "MUDDY","MUSIC","MAILS","MALES","MANES","MEALS","MEATS","MEETS","MELTS","MENUS",
        "MILES","MILLS","MINES","MINTS","MISTS","MOANS","MOLDS","MOLES","MOTHS","MOVES",
        "MULES","MATEY","MAXIM","MEALY","MEATY","MEDIC","MELEE","MELON","MESSY","MIDGE",
        "MINCE","MINTY","MOCHA","MOGUL","MOLDY","MOOSE","MOUSY","MUCKY","MUGGY","MATED",
        "MATER","MATES","MITER","MITRE","MITERS",
        // N
        "NAIVE","NERVE","NEVER","NIGHT","NOBLE","NOISE","NORTH","NOTCH","NOVEL","NURSE",
        "NYMPH","NAILS","NAMES","NECKS","NEEDS","NODES","NOSES","NOTES","NIFTY","NINNY",
        "NIPPY","NUTTY","NITER","NITRE",
        // O
        "OCEAN","OFFER","OLIVE","ONSET","ORDER","OTHER","OUTER","OWNER","OXIDE","OZONE",
        "OAKEN","ODDLY","OFFAL","OFTEN","ONION","ORBIT","OVOID","OATHS","OATER",
        // P
        "PAINT","PAPER","PARTY","PASTA","PATCH","PEARL","PENAL","PERCH","PHOTO","PIANO",
        "PIECE","PILOT","PINCH","PITCH","PIXEL","PIXIE","PLACE","PLAIN","PLANE","PLANK",
        "PLANT","PLATE","PLAZA","PLEAD","PLEAT","PLUCK","PLUMB","PLUME","PLUMP","PLUNK",
        "POINT","POLAR","POWER","PRESS","PRICE","PRIDE","PRIME","PRINT","PRIOR","PRIZE",
        "PROBE","PROOF","PROSE","PROUD","PROVE","PROWL","PULSE","PUNCH","PUPIL","PURSE",
        "PACES","PACKS","PAGES","PAINS","PALES","PALMS","PATHS","PEEKS","PEELS","PEERS",
        "PICKS","PILES","PILLS","PINES","PIPES","PLANS","PLAYS","PLOTS","PLUGS","POEMS",
        "POETS","POLES","POLLS","POOLS","PORES","PORTS","POSES","PANSY","PASTY","PATSY",
        "PEACH","PEAKY","PEEVE","PICKY","PINEY","PINKY","PLAID","PODGY","POOCH","POTTY",
        "POUTY","PRIVY","PRUNE","PUDGY","PUFFY","PURGE","PYGMY","PACED","PACER","PACERS",
        "PARER","PARED","PARES","PLIER","PLIED","PLIER","PLACE","PLACER","PLATE","PLATER",
        "PATER",
        // Q
        "QUEEN","QUERY","QUEST","QUICK","QUIET","QUOTA","QUOTE","QUACK","QUALM","QUELL",
        // R
        "RADAR","RADIO","RAISE","RANCH","RANGE","RAPID","RATIO","REACH","REACT","READY",
        "REALM","REIGN","RELAX","REPAY","REPLY","RIGHT","RIGID","RISKY","RIVAL","RIVER",
        "RIVET","ROBOT","ROCKY","ROUGE","ROUGH","ROUND","ROUTE","ROWDY","RULER","RURAL",
        "RUSTY","RACES","RACKS","RAILS","RAINS","RAKES","RAMPS","RANKS","RANTS","RATES",
        "READS","REELS","RENTS","RIDES","RINGS","RIOTS","RISES","RISKS","ROAMS","ROARS",
        "ROLLS","ROOFS","ROOMS","ROOTS","ROPES","ROSES","RUINS","RULES","RABID","RANGY",
        "RASPY","RAVEN","RECTO","REEDY","REGAL","RIPEN","RISEN","RUDDY","RUNNY","RATED",
        "RATER","RACER","RACED","RICER","RISEN",
        // S
        "SADLY","SAINT","SAUCE","SCALE","SCALP","SCAMP","SCANT","SCARF","SCENE","SCENT",
        "SCONE","SCOOP","SCOPE","SCORE","SCOUT","SCOWL","SCRAM","SCRAP","SCRUB","SEIZE",
        "SENSE","SEVEN","SHADE","SHAKE","SHALL","SHAME","SHAPE","SHARE","SHARP","SHEER",
        "SHONE","SHORE","SHOUT","SHOVE","SHRUB","SIEGE","SINCE","SIXTH","SIXTY","SKILL",
        "SKIRT","SKULL","SLACK","SLAIN","SLANT","SLASH","SLATE","SLAVE","SLEEK","SLEEP",
        "SLEET","SLICK","SLIDE","SLING","SLOPE","SMART","SMASH","SMELL","SMELT","SMILE",
        "SMITE","SMOKE","SNACK","SNAIL","SNAKE","SNARE","SNIFF","SNORE","SOLAR","SOLID",
        "SOUTH","SPACE","SPARK","SPAWN","SPEAK","SPEAR","SPEED","SPEND","SPICE","SPINE",
        "SPOKE","SPOON","SPRAY","SQUAD","STACK","STAFF","STAGE","STAIN","STAIR","STAKE",
        "STALE","STALL","STAMP","STAND","STARK","START","STASH","STATE","STEAM","STEEL",
        "STEEP","STEER","STERN","STICK","STIFF","STILL","STOCK","STONE","STOOD","STORM",
        "STORY","STOUT","STOVE","STRAP","STRAY","STRUM","STUCK","STUDY","STUFF","STUMP",
        "STUNG","STYLE","SUGAR","SUITE","SUNNY","SUPER","SURGE","SWEAR","SWEEP","SWEET",
        "SWEPT","SWIFT","SWING","SWIPE","SWOOP","SWORD","SAILS","SANDS","SCARS","SEALS",
        "SEAMS","SEEDS","SELLS","SENDS","SHINS","SHIPS","SHOES","SIGNS","SILLS","SINKS",
        "SIZES","SKINS","SLAPS","SLIPS","SLOTS","SLUGS","SNOBS","SOCKS","SOILS","SOLES",
        "SONGS","SORES","SORTS","SOULS","SOUPS","SPINS","SPITS","SPOTS","SPURS","STABS",
        "STAGS","STARS","STEMS","STEPS","STEWS","STOPS","STUBS","STUDS","SULKS","SURFS",
        "SWAPS","SCALD","SCALY","SEEDY","SERVE","SHADY","SHAKY","SLANG","SLIMY","SOGGY",
        "SOOTY","SOPPY","SOUPY","SPANK","SPARE","SPLAY","SPOOK","SPORE","SPRIG","SPUNK",
        "SPURN","SQUAT","SQUID","STAID","STOIC","STONY","STRAW","STRIP","STRUT","SULKY",
        "SULLY","SURLY","SWAMP","SATED","SKATER","SLATER","SLICER","SPACER","SPACED",
        // T
        "TABLE","TASTE","TAUNT","THORN","THREE","TIGER","TIRED","TITLE","TOAST","TOKEN",
        "TORCH","TOTAL","TOUCH","TOUGH","TOWER","TOXIC","TRACE","TRACK","TRADE","TRAIL",
        "TRAIN","TRAMP","TREAD","TREND","TRIBE","TRICK","TRIED","TROOP","TRUCK","TRULY",
        "TRUMP","TRUNK","TRUST","TRUTH","TULIP","TUMOR","TUNIC","TACKS","TALES","TALKS",
        "TEARS","TELLS","TENDS","TERMS","TESTS","TICKS","TIDES","TILLS","TIRES","TOADS",
        "TOLLS","TOMBS","TOMES","TONGS","TOURS","TRAMS","TRAPS","TRIPS","TROTS","TUBES",
        "TUFTS","TUNES","TURFS","TUSKS","TWINS","TYPES","TANGY","TARDY","TAWNY","TEPID",
        "TERSE","TESTY","TIDAL","TOADY","TODDY","TRILL","TRIPE","TRITE","TROUT","TUBER",
        "TURBO","TWANG","TWEED","TWILL","TIMED","TIMER","TONER","TONED","TONES","TAPER",
        "TAPED","TAPES","TAKER","TAKED","TALES","TAKEN","TABBY","TAFFY",
        // U
        "UNION","UNITY","UNTIL","UPPER","USAGE","UTTER","ULCER","ULTRA","UMBRA","UNDUE",
        "UNFIT","UNIFY","UNLIT","UNMET","UNPIN","UNTIE","UNWED","URBAN","USHER",
        // V
        "VAGUE","VALID","VAULT","VIGOR","VIRAL","VISIT","VISTA","VITAL","VIVID","VOCAL",
        "VOICE","VALES","VANES","VASES","VEILS","VEINS","VESTS","VIBES","VINES","VOIDS",
        "VOTES","VAPID","VIPER","VISOR","VIXEN","VODKA","VOMIT",
        // W
        "WALTZ","WASTE","WATCH","WATER","WEARY","WEAVE","WEDGE","WEIGH","WEIRD","WHALE",
        "WHEAT","WHEEL","WHERE","WHICH","WHILE","WHITE","WHOLE","WHOSE","WIDER","WIELD",
        "WINDY","WITCH","WOMAN","WOMEN","WORLD","WORRY","WORSE","WORST","WORTH","WOULD",
        "WRACK","WRATH","WREAK","WRECK","WROTE","WAGES","WALKS","WALLS","WANTS","WARDS",
        "WARNS","WARPS","WASPS","WAVES","WEEDS","WEEKS","WHIPS","WINDS","WINES","WINGS",
        "WIRES","WORMS","WRENS","WRITS","WACKY","WARTY","WEEDY","WIMPY","WINCE","WITTY",
        "WOODY","WOOZY","WORMY","WADER","WAGER","WAKEN","WAFER","WIRED",
        // Y
        "YOUNG","YOUTH","YAPPY","YUCKY","ZIPPY","ZONAL","ZESTY",
        // -ATE words and family
        "ABATE","AWAIT","IRATE","ELATE","GRATE","CRATE","PLATE","SLATE","SKATE","STATE",
        "STAVE","BRAVE","SHAVE","HEAVE","CLEAVE","LEAVE","WEAVE","HASTE","PASTE","TASTE",
        "WASTE","BASTE","BATED","RATED","MATED","SATED","HATED","DATED","FATED","GATED",
        "LATED","OATER","RATER","CATER","EATER","HATER","LATER","WATER","MATER","PATER",
        "TATER","PLATER","SKATER","SLATER","CRATER","GRATER","STATER","SKATED","SLATED",
        "CRATED","GRATED","STATED","PLATED","STATED","PLATES","SLATES","CRATES","GRATES",
        "SKATES","STATES","MATES","RATES","DATES","GATES","HATES","LATES","FATES","SATES",
        // -ACE words and family
        "PLACE","SPACE","TRACE","GRACE","BRACE","FACED","LACED","PACED","RACED","SPACED",
        "TRACED","PLACED","GRACED","BRACED","FACES","LACES","PACES","RACES","ACER","ICER",
        "DICER","NICER","RICER","RACER","LACER","FACER","PACER","SLICER","PRICER","PLACER",
        "SPACER","TRACER","RACER","GRACE","BRACE","PLACE","SPACE","TRACE",
        // -IRE words and family
        "SIRED","TIRED","HIRED","FIRED","MIRED","WIRED","SIRES","TIRES","HIRES","FIRES",
        "MIRES","WIRES","SIREN","LINER","DINER","MINER","FINER","VINER","TIMED",
        // -ORE words and family
        "BORED","CORED","GORED","PORED","TORED","BORES","CORES","GORES","PORES","LORES",
        "MORES","SORES","BORER","CORER","GORER","PORER","TORER","OVERT","OVERS","COVER",
        // -AKE words and family
        "BAKED","CAKED","FAKED","HIKED","LIKED","BIKED","RAKED","WAKED","BAKES","CAKES",
        "FAKES","RAKES","WAKES","BAKER","FAKER","MAKER","RAKER","TAKER","WAKER","SHAKEN",
        "TAKEN","AWAKEN","RAKER","MAKER",
        // -INE words and family
        "DINED","FINED","LINED","MINED","PINED","VINED","WINED","DINES","FINES","LINES",
        "MINES","PINES","VINES","WINES","DINER","FINER","LINER","MINER","VINER","WINER",
        // -IKE words and family
        "BIKED","HIKED","LIKED","PIKED","BIKED","HIKER","LIKER","BIKER","PIKER",
        // -ITE words and family
        "CITED","BITED","SITED","MITED","CITES","SITES","MITES","BITES","CITER","BITER",
        "LITER","MITER","NITER","TITER","LITRE","MITRE","NITRE","LITERS","MITERS","NITERS",
        "TITERS","BITERS","KITERS","DITERS","LITED","SITED","TITED",
        // Common 5-letter everyday words
        "AFOOT","AFOUL","AGLOW","AGONY","AGORA","AILED","AIMER","ALGAE","ALLAY","ALLOT",
        "ALTAR","AMASS","AMAZE","AMISS","AMOUR","ANNOY","APHID","APTLY","ARBOR","ARGOT",
        "ARTSY","ASCOT","ATONE","AWASH","BADLY","BAGEL","BAGGY","BAIZE","BALMY","BANDY",
        "BANJO","BARON","BAYLE","BAYOU","BEADY","BEEFY","BELIE","BELLE","BEZEL","BILGE",
        "BITTY","BLEEK","BLISS","BOGUS","BOSSY","BOXER","BUDDY","BURLY","CACHE","CADET",
        "CAMEO","CAPER","CARAT","CAULK","CHAFE","CHASM","CHIDE","CINCH","CLEFT","CLUCK",
        "CLUMP","CLUNG","COBIA","COLIC","COLON","CONDO","CONGA","COPSE","COUCH","COVET",
        "COZY","CRAZE","CREAK","CRIMP","CROAK","CRONE","CROON","CURLY","DADDY","DAFFY",
        "DAUNT","DECAL","DECAY","DECOY","DECRY","DELVE","DEVIL","DIGIT","DINGO","DINGY",
        "DIVOT","DOGGY","DOLLY","DOWDY","DROWN","DUCHY","DUMPY","DUNCE","DUSTY","DWARF",
        "DWELL","EASEL","EERIE","EGRET","ELBOW","ELOPE","EMBED","ERASE","ESSAY","ETHIC",
        "EXACT","EXERT","EXILE","EXPEL","EXULT","FANNY","FEIGN","FEMUR","FETCH","FIERY",
        "FISHY","FJORD","FLAKY","FLEET","FLINT","FLOSS","FLOUT","FLUME","FLUNK","FLUTE",
        "FORTE","FOYER","FRISK","FRIZZ","FRUMP","FUGUE","GAUDY","GAUZE","GAVEL","GAWKY",
        "GENRY","GERMS","GIRLK","GIZMO","GLINT","GLOGG","GLOAT","GLOOM","GLYPH","GNASH",
        "GNOME","GOUGE","GRIPE","GROOM","GROPE","GRUEL","GRUMP","GULCH","GUMBO","GUSTO",
        "HAIKU","HAMMY","HARDY","HAUTE","HAZEL","HEAVE","HEDGE","HELIX","HIPPY","HITCH",
        "HOAGY","HOMER","HORNY","HOUND","HOVER","HOWDY","HYENA","IDYLL","INANE","INCUR",
        "INDIE","INERT","INFER","INGOT","IRONY","ITCHY","JOUST","JUMPY","KAPOW","KIOSK",
        "KNACK","KNAVE","KNEEL","KNELT","LABEL","LAITY","LANKY","LARDY","LARGO","LATCH",
        "LEGGY","LIBEL","LILAC","LIMBO","LITHE","LIVID","LLAMA","LOBBY","LOFTY","LOOPY",
        "LORRY","LUMPY","MACHO","MAMBO","MEALY","MEATY","MEDIC","MELEE","MELON","MESSY",
        "MIDGE","MINTY","MOCHA","MOGUL","MOLDY","MOOSE","MOUSY","MUCKY","MUGGY","NIFTY",
        "NINNY","NIPPY","NUTTY","OAKEN","ODDLY","OFFAL","OFTEN","ONION","ORBIT","OVOID",
        "PANEL","PANSY","PASTY","PATSY","PEACH","PEAKY","PEEVE","PICKY","PINEY","PINKY",
        "PIXIE","PLAID","PODGY","POOCH","POTTY","POUTY","PRIVY","PRUNE","PUDGY","PUFFY",
        "PURGE","PYGMY","QUACK","QUALM","QUELL","RABBI","RABID","RADIX","RAMMY","RANGY",
        "RASPY","RAVEN","RECTO","REEDY","REGAL","RENEW","REPEL","RERUN","RHYME","RIPEN",
        "ROCKY","RUDDY","RUGBY","RUNNY","SAGGY","SANDY","SASSY","SAVVY","SCALY","SEDAN",
        "SEEDY","SHADY","SHAKY","SLANG","SLIMY","SOGGY","SONIC","SOOTY","SOPPY","SOUPY",
        "SPANK","SPARE","SPLAY","SPOOK","SPORE","SPRIG","SPUNK","SPURN","SQUAT","SQUID",
        "STAID","STOIC","STONY","STRAW","STRIP","STRUT","SULKY","SULLY","SURLY","SWAMP",
        "TABBY","TAFFY","TANGY","TAPIR","TARDY","TAWNY","TEPID","TERSE","TESTY","TIDAL",
        "TOADY","TODDY","TRILL","TRIPE","TRITE","TROTH","TROUT","TUBER","TUMID","TUBBY",
        "TULLE","TURBO","TWANG","TWEED","TWILL","ULCER","ULTRA","UMBRA","UNDUE","UNFIT",
        "UNIFY","UNLIT","UNMET","UNPIN","UNTIE","UNWED","URBAN","USHER","VEINY","VIPER",
        "VISOR","VIXEN","VODKA","VOMIT","WACKY","WARTY","WEEDY","WIMPY","WINCE","WITTY",
        "WOODY","WOOZY","WORMY","YAPPY","YUCKY","ZIPPY","ZONAL","ZESTY",
        // additional common words
        "SCRAM","SCRUB","SCRAWL","SPAWN","SPICE","SPINE","SPOKE","SPOON","SPRAY","SQUAD",
        "ABBOT","ABIDE","ACRID","ADAGE","ADEPT","ADOBE","AGAVE","AGILE","AGLOW","ALGAE",
        "ALLAY","ALLOT","ALOOF","ALTAR","AMASS","AMAZE","AMBLE","AMISS","AMOUR","ANNOY",
        "APHID","APRON","ARBOR","ARGOT","ASCOT","ASKEW","ATOLL","AWASH","BEADY","BELLE",
        "BEZEL","BILGE","BOSSY","BRAWL","BRAWN","BRAZE","BREAM","BRINE","BRISK","BROIL",
        "BULLY","CACHE","CADET","CAMEO","CAPER","CARAT","CAULK","CHAFE","CHASM","CHIDE",
        "CINCH","CLEFT","CLUCK","CLUMP","CLUNG","COBIA","COLIC","COLON","CONDO","CONGA",
        "COPSE","COUCH","COVET","CRAZE","CRIMP","CROAK","CRONE","CROON","CURLY","DAFFY",
        "DAUNT","DECAL","DECAY","DECOY","DECRY","DELVE","DEVIL","DIGIT","DINGO","DINGY",
        "DIVOT","DOGGY","DOLLY","DOLMA","DOWDY","DROWN","DUCHY","DUMPY","DUNCE","DUSTY",
        "DWARF","DWELL","EASEL","EERIE","EGRET","ELBOW","ELOPE","EMBED","EMCEE","ERASE",
        "ERODE","ETHIC","EVADE","EXPEL","EXULT","FANNY","FEIGN","FISHY","FJORD","FLAKY",
        "FLEET","FLINT","FLOSS","FLOUT","FLUME","FLUNK","FLUTE","FOAMY","FRISK","FRIZZ",
        "FRUMP","GAUDY","GAUZE","GAVEL","GAWKY","GECKO","GEESE","GIDDY","GLAZE","GLINT",
        "GLOGG","GLOOM","GLYPH","GNASH","GNOME","GOLLY","GOUGE","GRIPE","GROOM","GROPE",
        "GRUEL","GRUMP","GULCH","GUMBO","HAMMY","HAUTE","HEAVE","HELIX","HIPPO","HIPPY",
        "HITCH","HOAGY","HORNY","HOWDY","IMPEL","INGOT","KAPOW","KHAKI","KITTY","KNACK",
        "KNAVE","LAITY","LARDY","LARGO","LATCH","LEGGY","LIBEL","LILAC","LITHE","LLAMA",
        "LOBBY","LOOPY","LORRY","LUMPY","MACHO","MAMBO","MAXIM","MEALY","MEATY","MEDIC",
        "MELEE","MELON","MESSY","MIDGE","MINTY","MOCHA","MOGUL","MOLDY","MOOSE","MOUSY",
        "MUCKY","MUGGY","NINNY","NIPPY","PANEL","PASTY","PATSY","PEAKY","PEEVE","PICKY",
        "PINEY","PINKY","PLAID","PODGY","POOCH","POTTY","POUTY","PRIVY","PRUNE","PUDGY",
        "PUFFY","PURGE","PYGMY","QUACK","QUALM","QUELL","RABBI","RABID","RADIX","RAMMY",
        "RANGY","RASPY","RAVEN","RECTO","REEDY","REGAL","RENEW","REPEL","RERUN","RHYME",
        "RIPEN","RUDDY","RUGBY","RUNNY","SAGGY","SANDY","SASSY","SAVVY","SCALD","SCALP",
        "SCALY","SEDAN","SLANG","SLIMY","SONIC","SOPPY","SOUPY","SPANK","SPARE","SPLAY",
        "SPOOK","SPORE","SPRIG","SPUNK","SPURN","SQUID","STRAW","STRIP","STRUT","SULKY",
        "SULLY","SURLY","SWAMP","TABBY","TAFFY","TAPIR","TARDY","TAWNY","TEPID","TERSE",
        "TESTY","TIDAL","TOADY","TODDY","TRILL","TRIPE","TRITE","TROUT","TUBER","TUMID",
        "TUBBY","TULLE","TURBO","TWANG","TWEED","TWILL","ULCER","ULTRA","UMBRA","URBAN",
        "USHER","VEINY","VIPER","VISOR","VIXEN","VODKA","VOMIT","WIMPY","WINCE","WITTY",
        "WOODY","WOOZY","WORMY","YUCKY",
        // LITE and friends specifically requested
        "LITES","SATED","MATED","RATED","HATED","OATER","TALER","LATED","MITES","SITES",
        "CITES","KITES","BITES","DITES","DICER","RICER","NICER","SLICER","PRICER","LITE",
    ]
}
